### ISSUE TITLE
手机为什么会检测到有病毒呢？

### ISSUE THREAD

**Issue by zjh19990215** [MonsterNone/tmall-miao#1]

**Comment by MonsterNone** [comment]
我猜测可能是脚本里面含有url、淘宝链接、taobao://开头的scheme协议，手机管家根据关键字识别为诱导分享。

实际脚本无毒且不会读取隐私，apk权限均为auto.js默认。唯一的联网行为是检查更新。

附上查毒报告：![报告.jpg](https://i.loli.net/2020/06/02/vHCgFZ93GsdtKPS.jpg)

**Comment by MonsterNone** [comment]
已经通过重新签名打包加固解决此问题。
