### ISSUE TITLE
浏览任务完成后就不动了，是需要怎么操作吗还是正常结束了，谢谢

### ISSUE THREAD

**Issue by wangyuxiang985** [MonsterNone/tmall-miao#10]

**Comment by wangyuxiang985** [comment]
![Screenshot_2020-10-21-10-47-23-304_com.taobao.taobao.jpg](https://i.loli.net/2020/10/21/de8tOg9XHpcyPnk.jpg)

**Comment by MonsterNone** [comment]
是因为返回了主页，偶尔会出现这种情况，重新开一遍
