### ISSUE TITLE
华为mate20pro京东寻找任务控件太慢了

### ISSUE THREAD

**Issue by 941818924** [MonsterNone/tmall-miao#116]
大概要20-30s才能进入下一个任务，请问正常吗

**Comment by MonsterNone** [comment]
>  另外建议找不到控件停止任务的判定，增加一个返回再寻找任务入口的循环，因为有些任务进去会有弹窗，只有一次返回是回到此任务界面，而不是返回任务菜单

这个已经在V19/20优化了
