### ISSUE TITLE
电脑和手机都识别为病毒。。

### ISSUE THREAD

**Issue by miaowyg** [MonsterNone/tmall-miao#12]
如题

**Comment by miaowyg** [comment]
这个问题也还好，之前用过这个应用，应该没问题。 
 新疑问是   是因为xposed还是别的原因， 20000喵币的任务 只得100或者200，是为啥呀

**Comment by MonsterNone** [comment]
病毒是因为调用淘宝打开链接，被识别为推广。喵币变少可能是因为黑号了，具体原因未知，我两个号自用都没有出现这个情况。

**Comment by miaowyg** [comment]
> 病毒是因为调用淘宝打开链接，被识别为推广。喵币变少可能是因为黑号了，具体原因未知，我两个号自用都没有出现这个情况。

emmm 这就尴尬了，我开始以为是root或者xposed , 换了个 不用上述环境的手机还是一二百的喵币，没救了  。。。
