### ISSUE TITLE
被淘宝发现了

### ISSUE THREAD

**Issue by xiao-jay** [MonsterNone/tmall-miao#123]
淘宝版本为最新，用的小米8机型，用release的app进行自动任务，31号早上发现开的红包变成一分了，有三个淘宝号，都变成一分红包，两个淘宝号31号无法参加投色子活动，显示的是没有匹配到对手，明日给你匹配

**Comment by xiao-jay** [comment]
![IMG_1251](https://user-images.githubusercontent.com/87080562/139573877-df410c35-c7dd-4205-a74d-a0d06b0dd780.PNG)

**Comment by MonsterNone** [comment]
一个手机登3个号？

**Comment by xiao-jay** [comment]
装了auto.js，不知道是否会有影响

**Comment by HAHA009** [comment]
> 
> 
> 装了auto.js，但没使用，不知道是否会有影响

必然有影响。。。你开过就内存驻留了。。。

**Comment by xiao-jay** [comment]
但是我没有开启过它，只在上一年双十一使用过，这一年一直使用这个双十一助手

**Comment by MonsterNone** [comment]
> 但是我没有开启过它，只在上一年双十一使用过，这一年一直使用这个双十一助手

如果不用最好是卸了，我怀疑淘宝会读取使用无障碍的应用列表
