### ISSUE TITLE
京东在这一步不能运行

### ISSUE THREAD

**Issue by fjcqv** [MonsterNone/tmall-miao#125]
if (!findTextDescMatchesTimeout(/.*累计任务奖.*/, 8000)) {
        console.log('似乎没能打开任务列表，退出')
        quit()
    }

提示似乎没能打开任务列表，退出

**Comment by MonsterNone** [comment]
麻烦提供机型和具体截图

**Comment by MonsterNone** [comment]
试一下V25 abe447b
