### ISSUE TITLE
V24版本，进入京东以后，执行不了任务，直接返回两次，我的京东版本是V10.2.0

### ISSUE THREAD

**Issue by oranges12** [MonsterNone/tmall-miao#129]
页面显示 ：
进入活动页面
开始寻找列表
找到控件
寻找列表结束
进行一次试探性寻找
进入，稍后返回
返回
寻找未完成的任务
未找到浏览任务，退出

**Comment by MonsterNone** [comment]
返回是返回到了哪里？

**Comment by MonsterNone** [comment]
试一下V25 abe447b795712c72202bc709610c6d0c805b36d0
