### ISSUE TITLE
仅仅 去浏览，貌似不能覆盖到所有的吧，貌似还有 去完成、去施肥 之类的。

### ISSUE THREAD

**Issue by lesteryou** [MonsterNone/tmall-miao#13]
https://github.com/MonsterNone/tmall-miao/blob/c711d725a8ecbfc2d3189c553750a3567de4e519/start.js#L39

**Comment by MonsterNone** [comment]
有些任务太复杂（比如去施肥）。另外一些任务会在之后版本增加处理

**Comment by lijinrong** [comment]
还有去搜索按钮呢

**Comment by KKabc** [comment]
淘金币的活动有不？

**Comment by xuchenxc** [comment]
> 有些任务太复杂（比如去施肥）。另外一些任务会在之后版本增加处理

好的，期待

**Comment by MonsterNone** [comment]
已经实现
