### ISSUE TITLE
V25版本，进入京东以后，执行不了任务，直接返回两次到首页，我的京东版本是V10.2.2

### ISSUE THREAD

**Issue by fuziliang** [MonsterNone/tmall-miao#133]
页面显示 ：
进入活动页面
开始寻找列表
找到控件
寻找列表结束
进行一次试探性寻找
进入，稍后返回
返回
寻找未完成的任务
未找到浏览任务，退出

**Comment by hackedbyxx** [comment]
我也发现了，还没上个版本好用

**Comment by fuziliang** [comment]
> 我也发现了，还没上个版本好用

我的解决办法是在第一次返回到任务列表时，随便点击个任务进去。
这样第二次返回就不会到首页而是在任务列表，实测这样是可以运行任务的。
