### ISSUE TITLE
JD: 活动太火爆了

### ISSUE THREAD

**Issue by yizems** [MonsterNone/tmall-miao#136]
![image](https://user-images.githubusercontent.com/16949474/140535836-32d58a5c-7d4f-4df4-bd25-0d5c2985e5eb.png)

**Comment by zsxlrex** [comment]
+1

**Comment by fuluoduo2008** [comment]
唉，应该是狗东加强了检测。只能关闭脚本后台，手动做

**Comment by thinson** [comment]
我也遇到了这种状况，可我觉得不是检测后台，因为挂着后台手动点击时有效的，程序点击就显示活动火爆。

**Comment by guochong666** [comment]
我也遇到了这种情况

**Comment by wangguangyou** [comment]
自己手动打开京东 不要让脚本唤起

**Comment by hu516** [comment]
> 自己手动打开京东 不要让脚本唤起

原来如此，厉害了

**Comment by Yuqing-Xie** [comment]
> 自己手动打开京东 不要让脚本唤起

可以运行了，感谢

**Comment by dididili** [comment]
> 自己手动打开京东 不要让脚本唤起

具体咋操作啊，我事先打开jd，然后再点开始京东任务还是不行

**Comment by Yuqing-Xie** [comment]
> > 自己手动打开京东 不要让脚本唤起
> 
> 具体咋操作啊，我事先打开jd，然后再点开始京东任务还是不行

把京东退了，再手动重新开一个

**Comment by cfan005** [comment]
> > > 自己手动打开京东 不要让脚本唤起
> > 
> > 
> > 具体咋操作啊，我事先打开jd，然后再点开始京东任务还是不行
> 
> 把京东退了，再手动重新开一个

我这样操作了也不行。。。鸿蒙2.0

**Comment by dididili** [comment]
> > > 自己手动打开京东 不要让脚本唤起
> > 
> > 
> > 具体咋操作啊，我事先打开jd，然后再点开始京东任务还是不行
> 
> 把京东退了，再手动重新开一个

好的，谢谢老哥，我今天手动点完了，明天再试试

**Comment by tangmuyang** [comment]
似乎jd检测此app的无障碍服务。关闭掉无障碍服务就可以正常参与活动，服务一打开就是活动太火爆了

**Comment by cfan005** [comment]
> 似乎jd检测此app的无障碍服务。关闭掉无障碍服务就可以正常参与活动，服务一打开就是活动太火爆了

似乎是这样的，但没有无障碍服务这个脚本不就无法运行了

**Comment by Linus03** [comment]
可以自行基于源码打包解决，把包名和签名伪装一下其他正常的服务，例如`xx应用商店安装助手`这样的

**Comment by fjcqv** [comment]
目前测试鸿蒙不会出现这状况，另外京东app放在多开应用中（悟空分身、slimVXposed等）可以继续运行

**Comment by tangmuyang** [comment]
> 可以自行基于源码打包解决，把包名和签名伪装一下其他正常的服务，例如`xx应用商店安装助手`这样的

分享个包？

**Comment by shaoyingrui** [comment]
+1 火爆。。

**Comment by 89x98** [comment]
应该是检测包名了，我把这个app卸载了就可以手动做任务

**Comment by twy12689** [comment]
> 应该是检测包名了，我把这个app卸载了就可以手动做任务

不卸载也可以手动

**Comment by jackymardt** [comment]
手动也不行了，然后卸载京东，再安装，又可以了
