### ISSUE TITLE
JD火爆的，可以先打开APP，再打开脚本

### ISSUE THREAD

**Issue by twy12689** [MonsterNone/tmall-miao#139]
鸿蒙测试通过。
先打开京东app，再打开脚本，再运行任务。

**Comment by twy12689** [comment]
我一台荣耀（鸿蒙），一台一加，都可以，但是媳妇的华为（不行），但是不用卸载脚本，手动可以完成京东和京东金融任务。

**Comment by jackymardt** [comment]
如果手动也做不了了，可以卸载京东APP再装

**Comment by wstlxx** [comment]
我在小米手机上测试得到的情况是，安装谷歌三件套后，火爆，卸载后恢复正常。
推测是借用谷歌服务中的某些功能获取到安装了非法软件。
具体待验证

**Comment by tangmuyang** [comment]
> 我在小米手机上测试得到的情况是，安装谷歌三件套后，火爆，卸载后恢复正常。 推测是借用谷歌服务中的某些功能获取到安装了非法软件。 具体待验证

无效咧，你应用双开试试，反正双开出来的不行。不双开那有时候先开jd再开脚本app可以

**Comment by fuluoduo2008** [comment]
mate20不行，只要有脚本后台，手动做任务都提示火爆。。。
