### ISSUE TITLE
一人血书今天开启的JD年兽，TB新年活动

### ISSUE THREAD

**Issue by zhangsenpei** [MonsterNone/tmall-miao#145]
一人血书今天开启的JD年兽，TB新年活动

**Comment by MonsterNone** [comment]
有了 https://github.com/MonsterNone/tmall-miao/releases/latest

**Comment by zhangsenpei** [comment]
> 有了 https://github.com/MonsterNone/tmall-miao/releases/latest

牛批呀，有求必应，哈哈。
就是淘宝的还没

**Comment by zhangsenpei** [comment]
> 有了 https://github.com/MonsterNone/tmall-miao/releases/latest

大佬强无敌！
