### ISSUE TITLE
模拟器运行会出错。参考截图。

### ISSUE THREAD

**Issue by shaoyingrui** [MonsterNone/tmall-miao#147]
[![7knFYV.png](https://s4.ax1x.com/2022/01/09/7knFYV.png)](https://imgtu.com/i/7knFYV)

**Comment by MonsterNone** [comment]
模拟器我也没研究过T_T

**Comment by 1tothree** [comment]
能出一个跳过打开列表的版本吗 ，点击后延迟5s直接开始任务。
模拟器跟部分手机找不到列表控件卡住了。
想自己删几行结果发现直接报错了...
