### ISSUE TITLE
关于模拟器运行的集中讨论

### ISSUE THREAD

**Issue by MonsterNone** [MonsterNone/tmall-miao#153]
我先来：模拟器必须设置分辨率为竖屏，其次性能不能太弱

**Comment by MonsterNone** [comment]
根据群友`@辉夜`提供的测试，以下方案可用正常运行
```
蓝叠模拟器
竖屏模式，分辨率900*1600
DPI 320
2G或以上内存
不开root
```

**Comment by hdstar2009** [comment]
> 我先来：模拟器必须设置分辨率为竖屏，其次性能不能太弱

模拟器里京东app登录画轨迹一直失败，有啥窍门过吗

**Comment by MonsterNone** [comment]
> 模拟器里京东app登录画轨迹一直失败，有啥窍门过吗

我也搞不起来Orz.这导致我一直没法用模拟器测试

**Comment by mengkuku** [comment]
> 

主要得快，

**Comment by xxhhlk** [comment]
我用的蓝叠国际版（BlueStacks 5），Nougat 64位，京东有时候店铺会一直卡着加载不出来，并且CPU占用挺高，要杀掉京东再进去才行，另外还会时不时崩溃。CPU 8750h，GPU 1066
轨迹貌似滑的慢又稳的话，通过率会高一些（

**Comment by MonsterNone** [comment]
> 我用的蓝叠国际版（BlueStacks 5），Nougat 64位，京东有时候店铺会一直卡着加载不出来，并且CPU占用挺高，要杀掉京东再进去才行，另外还会时不时崩溃。CPU 8750h，GPU 1066 轨迹貌似滑的慢又稳的话，通过率会高一些（

看来还可能是京东的问题

**Comment by xxhhlk** [comment]
> 看来还可能是京东的问题
估计是x86模拟的还是不太兼容，用arm的云手机倒是没什么问题
