### ISSUE TITLE
运行一半遇到报错

### ISSUE THREAD

**Issue by guochong666** [MonsterNone/tmall-miao#156]
![Screenshot_2022-01-15-12-38-51-576_com jingdong app mall](https://user-images.githubusercontent.com/46960092/149609185-21fe4618-a110-40e5-9991-d0c038c38f19.jpg)

**Comment by sherlock-lqr** [comment]
v7版本——累计浏览并加购4个商品——等待累计浏览任务——等待进入商品列表——未能进入商品列表，返回——重新试探性寻找——重新打开任务列表——累计浏览........一直死循环

**Comment by MonsterNone** [comment]
> ![Screenshot_2022-01-15-12-38-51-576_com jingdong app mall](https://user-images.githubusercontent.com/46960092/149609185-21fe4618-a110-40e5-9991-d0c038c38f19.jpg)

20f7bcccbb1bcef43162920ac2f69fc2dc48ac90

> v7版本——累计浏览并加购4个商品——等待累计浏览任务——等待进入商品列表——未能进入商品列表，返回——重新试探性寻找——重新打开任务列表——累计浏览........一直死循环

557f1662e98739ec4c236ba9a48f6be652194522
