### ISSUE TITLE
图鉴中的额外任务

### ISSUE THREAD

**Issue by KelanMai** [MonsterNone/tmall-miao#158]
考虑添加这些其他额外任务吗？
![Uploading 1.png…]()

**Comment by MonsterNone** [comment]
图片好像没传上？

**Comment by KelanMai** [comment]
![1](https://user-images.githubusercontent.com/31427735/149918522-cb11cd8e-2cff-4919-966f-8ba485280cd1.png)
重新补上

**Comment by KelanMai** [comment]
这个任务比较繁琐   重复性叫多   那些任务都不用浏览时间   进去后是能直接返回完成

**Comment by MonsterNone** [comment]
刚打开吓我一跳哈哈，藏得好深。。OK稍后制作

**Comment by MonsterNone** [comment]
我看了一下，任务奖励几乎没有，都是些没营养的券，而且任务完成标识不明确。暂且不做它
