### ISSUE TITLE
炸年兽火爆问题

### ISSUE THREAD

**Issue by sparezgw** [MonsterNone/tmall-miao#159]
只要打开无障碍服务，就提示火爆。
关掉就正常了，应该是京东监测到无障碍服务中app的名字有年兽或者助手了吧。

**Comment by rquanx** [comment]
确实

**Comment by w-gitc** [comment]
进了活动页面再打开无障碍再启动脚本就能正常运行, 之后就正常用 不会出现火爆, 我的小米手机这样就可以了. miui12.5

**Comment by MonsterNone** [comment]
试下先打开京东app进入活动，然后打开脚本、授予无障碍权限、开始运行并选择手动打开京东
