### ISSUE TITLE
希望增加苹果版本

### ISSUE THREAD

**Issue by ttz0816** [MonsterNone/tmall-miao#16]

**Comment by Like-a-dog** [comment]
希望ios版 加1

**Comment by MonsterNone** [comment]
我能说我没有ios设备吗hhh直接在电脑上用安卓模拟器吧

**Comment by ttz0816** [comment]
试了雷电模拟器，然后发现没用，不过现在好像普遍黑号了，哈哈哈哈哈哈




| |
周涛
|
|
邮箱：17730017634@163.com
|

签名由 网易邮箱大师 定制

在2020年10月23日 09:22，MonsterNone 写道：

我能说我没有ios设备吗hhh直接在电脑上用安卓模拟器吧

**Comment by Like-a-dog** [comment]
哈哈哈 这个可以；但是 黑号的问题 能处理吗



17723000268@139.com
 
发件人： MonsterNone
发送时间： 2020-10-23 09:22
收件人： MonsterNone/tmall-miao
抄送： Ding; Comment
主题： Re: [MonsterNone/tmall-miao] 希望增加苹果版本 (#16)
我能说我没有ios设备吗hhh直接在电脑上用安卓模拟器吧
