### ISSUE TITLE
颜色判定优化

### ISSUE THREAD

**Issue by sparezgw** [MonsterNone/tmall-miao#160]
看了一下代码，只是在判断任务是否完成时，才会用到屏幕获取，颜色判定。
其实可以获取任务标题，最后有类似完成度提示(3/10)，通过数字是否相等来判断，就可以不用截图判断颜色了。

**Comment by MonsterNone** [comment]
年货节差不多结束了，618的时候通过这个完成试试。谢谢！

**Comment by MonsterNone** [comment]
7fc710dd8b0099862a49ab353b0dc0635a983d2c
