### ISSUE TITLE
用脚本完成任务会显示异常，如果不开脚本能正常点击 

### ISSUE THREAD

**Issue by lue611** [MonsterNone/tmall-miao#162]
版本是11
![150620462-59ccf73b-b62b-43a6-99b5-18c1a00640ce](https://user-images.githubusercontent.com/43984245/150645786-35e40c39-1874-4bb0-82ba-a4584a4dbe8c.jpg)

**Comment by MonsterNone** [comment]
你可以试下先打开京东app进入活动，然后打开脚本、授予无障碍权限、开始运行并选择手动打开京东
