### ISSUE TITLE
618京东活动开始

### ISSUE THREAD

**Issue by KelanMai** [MonsterNone/tmall-miao#164]
618京东活动今天开始了   我过来催更的   辛苦作者了~

**Comment by MonsterNone** [comment]
来了！上线了！

https://github.com/MonsterNone/tmall-miao/releases/latest

**Comment by google-mirror** [comment]
Good

**Comment by sherlock-lqr** [comment]
所以是啥活动，人在上海，连活动都看不了呜呜

**Comment by google-mirror** [comment]
> 来了！上线了！
> 
> https://github.com/MonsterNone/tmall-miao/releases/latest

不做一下每日签到吗

**Comment by MonsterNone** [comment]
> 不做一下每日签到吗


每日签到暂时不做
