### ISSUE TITLE
网易mumu模拟器，一直卡在等待页面加载

### ISSUE THREAD

**Issue by luanwulin** [MonsterNone/tmall-miao#17]
rt

**Comment by Jockio** [comment]
> rt

+1

**Comment by lucyyo** [comment]
雷电模拟器也是  +1

**Comment by MonsterNone** [comment]
安卓版本是多少

**Comment by lucyyo** [comment]
您好，我用的雷电模拟器模拟的







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MonsterNone/tmall-miao"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月23日(星期五) 上午9:22
收件人:&nbsp;"MonsterNone/tmall-miao"<tmall-miao@noreply.github.com&gt;;
抄送:&nbsp;"龚昕"<lucy_gx@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [MonsterNone/tmall-miao] 网易mumu模拟器，一直卡在等待页面加载 (#17)





 
安卓版本是多少

**Comment by MonsterNone** [comment]
> 
> 您好，我用的雷电模拟器模拟的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MonsterNone/tmall-miao" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月23日(星期五) 上午9:22 收件人:&nbsp;"MonsterNone/tmall-miao"<tmall-miao@noreply.github.com&gt;; 抄送:&nbsp;"龚昕"<lucy_gx@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [MonsterNone/tmall-miao] 网易mumu模拟器，一直卡在等待页面加载 (#17) 安卓版本是多少 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，也可能是分辨率的问题。调整成竖屏，确保“做任务”入口在屏幕上能看见
