### ISSUE TITLE
v2可以打开任务列表，但显示未打开

### ISSUE THREAD

**Issue by niuxvdong** [MonsterNone/tmall-miao#171]
![1f8efb7f5dc7504d99664d29bc6d9bb](https://user-images.githubusercontent.com/47845186/169739955-d9ae6bac-de20-4d58-9a9f-6e06059794a9.jpg)

**Comment by WhitLor** [comment]
同，米10pro/redmi K30，均为MIUI13稳定版，安卓12，提示未打开任务列表，实际已打开

**Comment by MonsterNone** [comment]
是什么版本的京东？

**Comment by MonsterNone** [comment]
> 这个是分身有术app里的分身

那手机原版京东是好的吗

**Comment by MonsterNone** [comment]
Duplicate of https://github.com/MonsterNone/tmall-miao/issues/173
