### ISSUE TITLE
似乎没能打开任务列表 综合反馈

### ISSUE THREAD

**Issue by WhitLor** [MonsterNone/tmall-miao#173]
![Screenshot_2022-05-23-14-52-27-188_com jingdong a](https://user-images.githubusercontent.com/34998894/169760691-371ef7d3-3dca-4f6a-8626-0cb1c1e591b7.jpg)

设备信息：MIUI13，安卓12，小米10Pro和K30

**Comment by besty99** [comment]
我也是MIUI13，安卓12    小米CV1S
脚本不能打开任务列表

**Comment by he007209** [comment]
同样，我是类原生

**Comment by scofield58** [comment]
V2
k30pro MIUI13 安卓12
似乎没能打开任务列表

**Comment by MonsterNone** [comment]
小米很迷惑，每次页面都和其他品牌不一样，甚至不同的小米手机也不一样。。。我这里再测试一下

**Comment by MonsterNone** [comment]
> ![Screenshot_2022-05-23-14-52-27-188_com jingdong a](https://user-images.githubusercontent.com/34998894/169760691-371ef7d3-3dca-4f6a-8626-0cb1c1e591b7.jpg)
> 
> 设备信息：MIUI13，安卓12，小米10Pro和K30

京东是最新版的吗？

**Comment by WhitLor** [comment]
> > ![Screenshot_2022-05-23-14-52-27-188_com jingdong a](https://user-images.githubusercontent.com/34998894/169760691-371ef7d3-3dca-4f6a-8626-0cb1c1e591b7.jpg)
> > 设备信息：MIUI13，安卓12，小米10Pro和K30
> 
> 京东是最新版的吗？

辛苦大佬，之前是play最新版10.5.4，不过我刚更新到应用商店最新11.0.2，也是同样问题

**Comment by MonsterNone** [comment]
> 辛苦大佬，之前是play最新版10.5.4，不过我刚更新到应用商店最新11.0.2，也是同样问题

刚发了个V3，尝试修复了一下，并增加了一个手动打开任务列表的选项；如果还是不行那我也暂时不太清楚了，我这里复现不出Orz.

**Comment by besty99** [comment]
V3版本我可以了，感谢大佬！

**Comment by MonsterNone** [comment]
> V3版本我可以了，感谢大佬！

那就好，那就好

~~每次活动修小米机型的bug都很头疼~~

**Comment by MonsterNone** [comment]
目前的一个问题是我这里无法复现，正在想办法

如果有能力分析的可以帮忙研究一下

**Comment by 1stCloudStrife** [comment]
K40 MIUI13 play版10.5.4

**Comment by 1stCloudStrife** [comment]
![Screenshot_2022-05-24-08-35-49-106_com jingdong app mall](https://user-images.githubusercontent.com/106125857/169925917-a502b9b9-16a1-4312-ac46-0eb1882c53d3.jpg)
k40 miui13 play版10.5.4

**Comment by bilibili20001** [comment]
Xperia 1 II
Android 12
Play版 10.5.4
https://user-images.githubusercontent.com/70944645/169832007-4240213c-b81b-4511-acb3-b1625f684537.png

**Comment by MonsterNone** [comment]
V4你们可以尝试下，我也不确定有没有真的修好。 @Torrin23 @WhitLor @he007209 @1stCloudStrife  @bilibili20001

**Comment by he007209** [comment]
> V4你们可以尝试下，我也不确定有没有真的修好。 @Torrin23 @WhitLor @he007209 @1stCloudStrife  @bilibili20001 

谢谢老哥，刚刚试了还是那样[Screenshot_20220524-112913_京东.png](https://user-images.githubusercontent.com/73971621/169943090-c7861d9c-2412-4d94-b7df-a8ee91ba2bfc.png)

**Comment by 1stCloudStrife** [comment]
> V4你们可以尝试下，我也不确定有没有真的修好。 @Torrin23 @WhitLor @he007209 @1stCloudStrife @bilibili20001
没有好，一样的情况

**Comment by MonsterNone** [comment]
> 谢谢老哥，刚刚试了还是那样[Screenshot_20220524-112913_京东.png](https://user-images.githubusercontent.com/73971621/169943090-c7861d9c-2412-4d94-b7df-a8ee91ba2bfc.png)

好吧，我是真不知道为啥了🤣始终复现不出这个问题

**Comment by MonsterNone** [comment]
> 谢谢老哥，刚刚试了还是那样[Screenshot_20220524-112913_京东.png](https://user-images.githubusercontent.com/73971621/169943090-c7861d9c-2412-4d94-b7df-a8ee91ba2bfc.png)

发现了一个情况，是不是因为悬浮窗挡住“累计任务奖励”这个文字（这是判定任务列表的标志）？方便的话试一下`不自动打开京东`，然后把软件悬浮窗点击`X`关掉或者点击`—`缩小，再打开京东活动，打开任务列表试下

**Comment by Q761109021** [comment]
V4版打不开任务列表.一加8T，第一次能打开做一个任务，然后就不行了。

**Comment by Q761109021** [comment]
> > 谢谢老哥，刚刚试了还是那样[Screenshot_20220524-112913_京东.png](https://user-images.githubusercontent.com/73971621/169943090-c7861d9c-2412-4d94-b7df-a8ee91ba2bfc.png)
> 
> 发现了一个情况，是不是因为悬浮窗挡住“累计任务奖励”这个文字（这是判定任务列表的标志）？方便的话试一下`不自动打开京东`，然后把软件悬浮窗点击`X`关掉或者点击`—`缩小，再打开京东活动，打开任务列表试下
> 
> 或者选自动打开京东，但是在选择自动之前关掉悬浮窗

关掉悬浮窗还是不行。

**Comment by MonsterNone** [comment]
我手持k30，miui 13内测版（5.20），京东特意安装了play 10.5.4，字体大小试了，显示大小试了，还是复现不出

**Comment by administer888** [comment]
realme q3pro也不行，是只有小米能用吗

**Comment by MonsterNone** [comment]
> realme q3pro也不行，是只有小米能用吗

是除了小米大部分机型都能用，oppo系（包括一加）可能会出现问题

**Comment by lll423** [comment]
> V4你们可以尝试下，我也不确定有没有真的修好。 @Torrin23 @WhitLor @he007209 @1stCloudStrife @bilibili20001

手机 小米mix 2s 系统是lineageOS 18.1  装了V4版本   还是出现 “似乎没能打开任务列表，退出”   实际已经打开

**Comment by Gibson256** [comment]
手机小米6x，系统是类原生安卓10，安装了V5版本，还是出现“似乎无法打开任务列表，退出”实际已经打开

**Comment by MonsterNone** [comment]
> 手机小米6x，系统是类原生安卓10，安装了V5版本，还是出现“似乎无法打开任务列表，退出”实际已经打开

好吧V5也不行，我都无语了

**Comment by MonsterNone** [comment]
出现`似乎没能打开`且有兴趣帮忙测试的朋友可以加一下我Q 3350786255

**Comment by lll423** [comment]
> lineageOS

v5版本 似乎没能打开任务列表 如下图

![image](https://user-images.githubusercontent.com/4048921/170031251-504b1527-1a6d-46dc-b007-8a5afed06000.png)

**Comment by 1stCloudStrife** [comment]
> Reference in new issue

红米K40 安卓12 MIUI13开发版 play版10.5.4

**Comment by 1stCloudStrife** [comment]
> 你们都是什么手机、什么系统（安卓版本、原厂系统/第三方）、什么版本的京东？（下面不用贴运行截图了，都差不多）

红米K40 安卓12 MIUI13开发版 play版10.5.4

**Comment by 1stCloudStrife** [comment]
我另外一台小米9 安卓11 miui13(官改) 国内最新版 能获取到任务没有问题

**Comment by MonsterNone** [comment]
> 我另外一台小米9 安卓11 miui13(官改) 国内最新版 能获取到任务没有问题

我也就很无奈，我的k30 安卓12，miui13开发版稳定版，京东play版国内版，都试了不出现这个问题。

~~再来我都要怀疑是号的问题~~目前我怀疑是webview的锅

**Comment by MonsterNone** [comment]
> > 你们都是什么手机、什么系统（安卓版本、原厂系统/第三方）、什么版本的京东？（下面不用贴运行截图了，都差不多）
> 
> 红米K40 安卓12 MIUI13开发版 play版10.5.4

麻烦问一下这个的webview是什么版本的？

**Comment by 1stCloudStrife** [comment]
> > 我另外一台小米9 安卓11 miui13(官改) 国内最新版 能获取到任务没有问题
> 
> 我也就很无奈，我手上的k30 安卓12，miui13开发版稳定版，京东play版国内版，都试了不出现这个问题。
> 
> ~再来我都要怀疑是号的问题~目前我怀疑是webview的锅

你这么一说，我是用谷歌商店把webview更新到最新稳定版（101.0.4951.61）了，刚刚试着卸载还原到miui默认的webview版本（96.0.4664.104），好了🤣，就是他的锅

**Comment by administer888** [comment]
大佬修一下OPPO系吧，毕竟用的人也不少😭

**Comment by MonsterNone** [comment]
> 大佬修一下OPPO系吧，毕竟用的人也不少😭

你看看你的手机webview是什么版本，应该和小米差不多原因。（在设置-应用管理里面，显示系统应用之后能找到webview）

**Comment by administer888** [comment]
对的，解决了，也是webview的问题

**Comment by he007209** [comment]
还真是，卸掉101的WebView就好了🤣

**Comment by HomeQi** [comment]
大佬模拟器目前没有好的方法嘛，我测了很多个都会在活动页面卡退，然后App重启。。。

**Comment by MonsterNone** [comment]
> 大佬模拟器目前没有好的方法嘛，我测了很多个都会在活动页面卡退，然后App重启。。。

那个是因为性能问题，我本地测试逍遥模拟器（最新版，好像是逍遥8）完美运行；夜神就不行总是卡。

**Comment by MonsterNone** [comment]
经过测试，最后一个可用的webview版本为`100.0.4896.127`，从`101.0.4951.41`开始就无法找到任务列表了

**Comment by dalu-test** [comment]
K30pro、MIUI 13、play版京东

目前卸载掉101版本的webview，完美运行

**Comment by Gibson256** [comment]
小米6x，系统是类安卓10，安装了V5版本，卸掉webview，成功运行

**Comment by lll423** [comment]
> 手机 小米mix 2s 系统是lineageOS 18.1（android 11） 装了V4版本 还是出现 “似乎没能打开任务列表，退出” 实际已经打开

手机 小米mix 2s 系统是lineageOS 18.1（android 11） 装了V5版本  卸载10版本的webview 再装上99版本号的webview  成功运行

**Comment by zzw19921212** [comment]
> 下午用appium、openatx/uiautomator2、原生uiautomator2都测试了一下，均无法获取101以上的控件，估计一时半会儿没法实现101的自动操作。暂时用国内版京东或者老版本webview吧。

麻烦大佬以后修复下101版本的webview

**Comment by MonsterNone** [comment]
> > 下午用appium、openatx/uiautomator2、原生uiautomator2都测试了一下，均无法获取101以上的控件，估计一时半会儿没法实现101的自动操作。暂时用国内版京东或者老版本webview吧。
> 
> 麻烦大佬以后修复下101版本的webview

webview的问题，我没法修复，不想降级webview就换国内版京东

**Comment by zzw19921212** [comment]
国内京东试过的，不行

MonsterNone ***@***.***> 于 2022年5月26日周四 08:46写道：

**Comment by MonsterNone** [comment]
@zzw19921212 可能是不同渠道版本还不一样，我用小米应用商店版未出现问题。那就只能降级webview了，100版本还是可以的。

**Comment by zzw19921212** [comment]
好吧，谢谢

MonsterNone ***@***.***> 于 2022年5月26日周四 22:19写道：

**Comment by xiaofeivip** [comment]
15版本也出现了，建议弄个手动打开选项
