### ISSUE TITLE
V3，似乎没能打开任务列表，实际已打开

### ISSUE THREAD

**Issue by lll423** [MonsterNone/tmall-miao#175]
与V2 一样的图，小米mix 2S 刷了 lineageOS 18.1

**Comment by MonsterNone** [comment]
这个问题我暂时无法解决，抱歉；我这里三个设备（华为、小米、魅族）都无法复现出T_T

欢迎pr，“似乎没能打开”的判定逻辑在https://github.com/MonsterNone/tmall-miao/blob/master/start_jd.js#L100

**Comment by MonsterNone** [comment]
Duplicate of #173
