### ISSUE TITLE
希望增加一个自动签到的功能

### ISSUE THREAD

**Issue by haiya512** [MonsterNone/tmall-miao#182]
如题

**Comment by MonsterNone** [comment]
是哪个的签到？

**Comment by MonsterNone** [comment]
> > 是哪个的签到？
> 
> 它应该指的是19亿的活动页，右边靠上那个每日签到，那个也是瓜分红包的。

原来如此，明天弄一个

**Comment by MonsterNone** [comment]
a9756e083e6beb284ed6293e2e5dd7ca8798ee1a

**Comment by google-mirror** [comment]
> > > 是哪个的签到？
> > 
> > 
> > 它应该指的是19亿的活动页，右边靠上那个每日签到，那个也是瓜分红包的。
> 
> 原来如此，明天弄一个

头上的金币的顺便收一下呗

**Comment by MonsterNone** [comment]
> > > > 是哪个的签到？
> > > 
> > > 
> > > 它应该指的是19亿的活动页，右边靠上那个每日签到，那个也是瓜分红包的。
> > 
> > 
> > 原来如此，明天弄一个
> 
> 头上的金币的顺便收一下呗

298dc1ef7388266f55fc0fa852d12a83e65a909c
