### ISSUE TITLE
越来越好用了,能否加多个京东金融

### ISSUE THREAD

**Issue by lionkingc** [MonsterNone/tmall-miao#184]
如题, 京东主程序任务能自动做齐了, 还有"京东金融"和微信小程序这两块需要手工做,感谢

**Comment by MonsterNone** [comment]
感谢支持！京东金融因为涉及到钱，比较敏感，所以不做自动任务；之后淘宝任务里面的支付宝也是。

**Comment by didiaoa** [comment]
请问能加微信小程序这个吗？

**Comment by didiaoa** [comment]
大佬，微信小程序还有逛店铺扔色子的活动，每个店铺有6次机会，每次必中1000金币，总共有40个店铺，全部完成一天有24万金币。不过有时候加购的任务提示加购失败。

**Comment by didiaoa** [comment]
![微信图片_20220525231937](https://user-images.githubusercontent.com/106248977/170298771-6246fb10-3851-4437-9ac0-5a0b384024d7.png)
![微信图片_202205252319371](https://user-images.githubusercontent.com/106248977/170298894-76bf7dc9-b3f3-4e58-a224-2afdbef0b262.png)

**Comment by yuki-007** [comment]
求更微信小程序

**Comment by ququyq** [comment]
能不能搞个pdd版本滴，大神~~

**Comment by FH0904** [comment]
可以搞个各大app 里面的浇水任务吗

**Comment by geelinsir** [comment]
> 可以搞个各大app 里面的浇水任务吗

有另外的项目，别跟618混一起了，目标太大

**Comment by haiya512** [comment]
> > 可以搞个各大app 里面的浇水任务吗
> 
> 有另外的项目，别跟618混一起了，目标太大

详细说说
