### ISSUE TITLE
测试最新第六版发现不行

### ISSUE THREAD

**Issue by zzw19921212** [MonsterNone/tmall-miao#186]
第六版测试不行。。。请修复
![Screenshot_20220525_143657](https://user-images.githubusercontent.com/30192107/170196527-33f3cedb-6f18-492b-8f9c-d056d5496804.jpg)

**Comment by zzw19921212** [comment]
机型为iqoo neo3，android12

**Comment by MonsterNone** [comment]
什么版本的京东？什么版本的webview？

**Comment by MonsterNone** [comment]
Duplicate of #173

**Comment by zzw19921212** [comment]
> 什么版本的京东？什么版本的webview？

京东是Googleplay版10.5.4，后来又尝试国内最新版本11.0.2还是不行。webview版本是101.0.4951.61

**Comment by MonsterNone** [comment]
> 京东是Googleplay版10.5.4，后来又尝试国内最新版本11.0.2还是不行。webview版本是101.0.4951.61

脚本日志写了，101及以上版本webview无法运行，卸载更新就可以了。具体见#171

**Comment by zzw19921212** [comment]
哦哦好的谢谢

MonsterNone ***@***.***> 于 2022年5月25日周三 20:21写道：
