### ISSUE TITLE
京东-入会任务之后无法返回继续

### ISSUE THREAD

**Issue by shyskyboy** [MonsterNone/tmall-miao#187]
![微信图片_20220525150556](https://user-images.githubusercontent.com/20738555/170201188-1e355d3a-b9d2-4c38-83c7-1263ab6ae9b5.jpg)

**Comment by MonsterNone** [comment]
等个至多60秒应该能自动返回？

**Comment by MonsterNone** [comment]
理论上流程没问题，小修了一下，如果还是卡住继续反馈吧 c479906c9b07b3b0b84dec649f4e38d49404c397

**Comment by shyskyboy** [comment]
ok，感谢大佬

**Comment by MonsterNone** [comment]
我发现还是会返回的时候卡住，虽然等个几十秒之后能自动返回。这个问题有待研究。
