### ISSUE TITLE
直接用autoJS跑可以吗？

### ISSUE THREAD

**Issue by s1sunny** [MonsterNone/tmall-miao#188]
首先感谢大佬的付出与分享！
问题是：
除了[start_jd.js](https://github.com/MonsterNone/tmall-miao/blob/master/start_jd.js)，看到项目里还有一个[ui.js](https://github.com/MonsterNone/tmall-miao/blob/master/ui.js)的文件，不知道是不是必要的文件？
能单独用start_jd在autoJS跑吗？会有功能缺失吗?

**Comment by MonsterNone** [comment]
不用，直接start_jd就可以
