### ISSUE TITLE
BUG反馈；入会

### ISSUE THREAD

**Issue by s1sunny** [MonsterNone/tmall-miao#189]
入会的任务有2种打钩的，一种在上的可以正常完成。
另外一种在下方的无法完成，勾选框在悬浮LOGO附近。等我截图上传。

另外签到也不太正常，会有红色字报错，等截图上传。

**Comment by s1sunny** [comment]
![微信图片_20220525223818](https://user-images.githubusercontent.com/51485377/170289202-b71f82f3-67e2-4bc8-ac03-4b4d813bf01d.jpg)
![微信图片_20220525223829](https://user-images.githubusercontent.com/51485377/170289213-34bb9a08-058d-4753-a54f-31b8148bac11.jpg)
![微信图片_20220525223839](https://user-images.githubusercontent.com/51485377/170289223-c170d34e-916a-4666-a395-2a1daa0dc1da.jpg)
分别为签到运行异常（我怀疑是不是第一次运行才会，今天是我第一次使用您的脚本），以及两个无法入会的截图。

再次感谢您的付出！

**Comment by MonsterNone** [comment]
入会暂时没好办法，因为无法拖动元素，且入会授权的选择按钮无法通过控件点击，只能通过坐标，目前选择的是元素中心坐标，如果出现浮窗遮档就GG了；

签到我怀疑是第一次运行的问题，你看有个浮窗遮挡了，我账号都不是第一次签到所以也不太清楚具体情况，之后我换个新账号看看修复一下。

另外您客气🌹

**Comment by MonsterNone** [comment]
我记得这个入会的浮窗好像也无法通过无障碍检测到，不然可以判断是否和授权选择重叠。稍后我再研究下

**Comment by MonsterNone** [comment]
入会支持自动移开 91c4a394c0b503607242d365c5a6308df5504a6c
