### ISSUE TITLE
打开任务列表失败

### ISSUE THREAD

**Issue by theWangs** [MonsterNone/tmall-miao#191]
我没法传图片，报错如下
打开任务列表
undefined TypeError Cannot call method clickable of null
卡住在活动页面，任务列表无法打开

京东V11.0.2 build 97548
小米11 MIUI13.0.8
软件第八版

另外，如果可以的话，可以在界面加一个重新开始任务不，省去了每次报错需要关掉，重新打开软件开始

**Comment by Pikarziur** [comment]
貌似不是不可以，但是如果无限报错时候，那可能就无限跑脚本，停不下来

**Comment by MonsterNone** [comment]
是的如楼上所说，自动重启任务可能会导致死循环

**Comment by MonsterNone** [comment]
你这个问题我暂时无法复现，先把`自动打开京东`关掉手动运行吧，我大概知道是什么问题，要是哪天复现了修一下

**Comment by MonsterNone** [comment]
换了个检测词，V9更新之后你再试一下
