### ISSUE TITLE
618第八版（修复第七版）报错了

### ISSUE THREAD

**Issue by google-mirror** [MonsterNone/tmall-miao#192]
![Screenshot_2022-05-26-10-28-46-171_com jingdong app mall](https://user-images.githubusercontent.com/70927995/170403554-5be78c5a-68f2-4297-a30b-594c5205510a.jpg)

另外有些领取的有的话, 也可以自动点了吧, 比如
![11111](https://user-images.githubusercontent.com/70927995/170403758-83b76e3d-d47f-441e-921b-82f4844f2181.jpg)

**Comment by Pikarziur** [comment]
大佬忘记赋值给next了

**Comment by MonsterNone** [comment]
> let next = textContains('开心收下 开心收下').findOne(5000)

我超还真是！感谢！

**Comment by MonsterNone** [comment]
@google-mirror 去领取这个按钮无法自动，按钮控件是一个图片，无法判读到底是去领取还是去完成，所以没法自动做

**Comment by MonsterNone** [comment]
我发现这个签到弹窗不影响运行，而且有些机型控件不一样，干脆不自动关闭了

**Comment by 1358939382** [comment]
京东小程序也有对应的任务

**Comment by Pikarziur** [comment]
> 按钮控件是一个图片，无法判读到底是去领取还是去完成，所以没法自动做



> @google-mirror 去领取这个按钮无法自动，按钮控件是一个图片，无法判读到底是去领取还是去完成，所以没法自动做

首页浮层，这个按钮用别的方法还算可以点击，但是我不会写怎么判断出现然后执行，所以我是在所有任务完成后添加这几行代码

    if (textContains('首页浮层').findOnce()) {
        let 浮层奖励 = textContains('首页浮层').findOnce().parent().child(3)
        浮层奖励.click();
        sleep(1000);
    }

**Comment by Pikarziur** [comment]
> @google-mirror 去领取这个按钮无法自动，按钮控件是一个图片，无法判读到底是去领取还是去完成，所以没法自动做

首页浮层，这个按钮用别的方法还算可以点击，但是我不会写怎么判断出现然后执行，所以我是在所有任务完成后添加这几行代码

if (textContains('首页浮层').findOnce()) {
    let 浮层奖励 = textContains('首页浮层').findOnce().parent().child(3)
    浮层奖励.click();
    sleep(1000);
}

**Comment by MonsterNone** [comment]
> if (textContains('首页浮层').findOnce()) {
> let 浮层奖励 = textContains('首页浮层').findOnce().parent().child(3)
> 浮层奖励.click();
> sleep(1000);
> }

主要是无法判断是否需要完成，有可能已完成，有可能未完成
