### ISSUE TITLE
需要入会的时候勾选按钮被悬浮抽奖图片遮挡

### ISSUE THREAD

**Issue by fengtu957** [MonsterNone/tmall-miao#194]
![3151653549639_ pic_thumb](https://user-images.githubusercontent.com/33717018/170439251-438b1316-4d8d-4f42-b9eb-4072c816a4cf.jpg)

**Comment by MonsterNone** [comment]
使用V9，V9能自动移开悬浮窗。这个图太糊了我也不确定是你没用V9，还是V9出了bug。

**Comment by fengtu957** [comment]
哦哦、好的
