### ISSUE TITLE
你们用的啥版本？我的逍遥模拟器的京东看不到浏览时间！只有官网的可以！但是贼卡老闪退！

### ISSUE THREAD

**Issue by xjd008** [MonsterNone/tmall-miao#201]
有没有大哥给个稳定版本？还能完美做任务的！

**Comment by MonsterNone** [comment]
我自己电脑上测试`逍遥模拟器最新版`，分辨率`竖屏（1280那个）`，京东`11.0.2`运行没问题。给的模拟器配置是`高`

**Comment by exlife1** [comment]
同逍遥，是看不到浏览时间 但能做任务。

**Comment by lionkingc** [comment]
夜神,设了4核, 京东正常,淘宝做不了

**Comment by lionkingc** [comment]
> 我自己电脑上测试`逍遥模拟器最新版`，分辨率`竖屏（1280那个）`，京东`11.0.2`运行没问题。给的模拟器配置是`高`

我试了, 逍遥最新版, Android 7.1 64BIT   1280手机 , 京东用的官网下的,可以做几秒,然后就会不停的京东崩了退出.
删除改用逍遥市场里的京东<v8.3.6>, 不会崩, 但是获取金币false,任务也启动不出来
