### ISSUE TITLE
为啥apk版本可以，直接用auto js就未能进入活动

### ISSUE THREAD

**Issue by ChangWeiBa** [MonsterNone/tmall-miao#203]
手机：华为Mate 40 Pro
 jd版本：for harmony os11.0.2 build97567 
auto js：8.8.13  
webview ：92
![微信图片_20220527115316](https://user-images.githubusercontent.com/20971864/170626102-fb3005cf-efa8-403a-a9e5-af97155994fd.jpg)

**Comment by MonsterNone** [comment]
代码是基于autojs 4.1.1版本的，没试过autojs8运行效果

**Comment by ChangWeiBa** [comment]
哦哦
