### ISSUE TITLE
热爱奇旅添加不到购物车

### ISSUE THREAD

**Issue by s4531625** [MonsterNone/tmall-miao#206]
大佬，刚刚新增的热爱奇旅，有时候会出现添加不到购物车
![1111](https://user-images.githubusercontent.com/106299978/170663839-16e807cd-5ce5-491e-8e34-9a18289b74b7.jpg)

**Comment by MonsterNone** [comment]
我也发现这个问题，偶尔出现；分析了一下好像是因为元素没有刷新，这个页面大概过个30秒就能找到商品了，但是如果运行中等30秒太慢了。
当然也可能是其他原因，我再研究一下情况，实在不行就等待至多30秒

**Comment by kinghunki** [comment]
这是因为商品无货或不支持当前地区销售，就会出现无法加购！

**Comment by MonsterNone** [comment]
这倒是，也有这种情况，特别是手机商品

> 这是因为商品无货或不支持当前地区销售，就会出现无法加购！

**Comment by MonsterNone** [comment]
等待20秒 ea36088153110ac2b003307e35d982c382d881d2

**Comment by MonsterNone** [comment]
另外加上一个不强制停止 dc4f091f2b6479b13be4d54b28ec55d2535dd042

**Comment by exlife1** [comment]
> 我也发现这个问题，偶尔出现；分析了一下好像是因为元素没有刷新，这个页面大概过个30秒就能找到商品了，但是如果运行中等30秒太慢了。 当然也可能是其他原因，我再研究一下情况，实在不行就等待至多30秒

我手动加购碰到失败的情况都是因为该商品为618预售商品只有支付定金按钮无加购按钮
