### ISSUE TITLE
不能自动点击“去领取”

### ISSUE THREAD

**Issue by mssm-mssm** [MonsterNone/tmall-miao#208]
红米k20P

**Comment by mssm-mssm** [comment]
![微信图片_20220528112105](https://user-images.githubusercontent.com/106417778/170808101-2ab30a18-ae5f-41cd-a3a6-ba516ae1fec7.jpg)

**Comment by mssm-mssm** [comment]
![微信图片_20220528112105](https://user-images.githubusercontent.com/106417778/170808160-52991aa9-31ec-4cf8-b92e-d1e726b6f65b.jpg)

**Comment by MonsterNone** [comment]
这个去领取无法设计自动点击
