### ISSUE TITLE
品牌墙BUG反馈

### ISSUE THREAD

**Issue by s1sunny** [MonsterNone/tmall-miao#210]
脚本版本：V11
运行环境：autoJS 4
手机：小米9
问题：品牌墙会报错卡住，具体在呼出京东APP内小程序的时候无法正确返回。目前V10可以正常使用。
报错信息见截图。
感谢大佬的付出！
![微信图片_20220528170142](https://user-images.githubusercontent.com/51485377/170818675-fd1de73a-34aa-4cf2-9b55-34838cbece63.jpg)

**Comment by MonsterNone** [comment]
收到，稍后看一下什么情况

**Comment by MonsterNone** [comment]
试图修了一下，但是理论上V10和V11的品牌墙代码是一样的
