### ISSUE TITLE
京东基本完美,淘宝问题报告

### ISSUE THREAD

**Issue by lionkingc** [MonsterNone/tmall-miao#212]
准备打开任务列表<此时会打不开> ,
默认方式打开失败,二次尝试<成功打开>
准备搜索任务
寻找任务入口...
[JavaException:java.lang.ArrayIndexOutOfBoundsException:length=0;index=0]
[JavaException:java.lang.ArrayIndexOutOfBoundsException:length=0;index=0]
没找到合适的任务.也许任务已经全部做完<实际一个都还没做过>

**Comment by MonsterNone** [comment]
收到，我研究一下什么情况，我这里暂时还没出现

**Comment by lionkingc** [comment]
> 收到，我研究一下什么情况，我这里暂时还没出现

可能因为我用的是模拟器, 没安卓机,用的夜神模拟器, 京东正常,淘宝做不了, 分辨率900*1600, 系统Android9 64bit

**Comment by bigmengbig** [comment]
为啥我用模拟器，打开活动直接闪退了

**Comment by lionkingc** [comment]
> 为啥我用模拟器，打开活动直接闪退了

夜神,android 9 ,64bit

**Comment by Loongson-NJ** [comment]
我用nova7 se手机也会这个样子

**Comment by MonsterNone** [comment]
模拟器好像往年也不太一样，我之后弄个模拟器试一下
