### ISSUE TITLE
京东入会任务貌似不能自动授权同意协议

### ISSUE THREAD

**Issue by Mading706** [MonsterNone/tmall-miao#213]
![Screenshot_20220529_120048_com jingdong app mall](https://user-images.githubusercontent.com/64320049/170851664-1af22c8a-1ba6-43f0-a68f-ed49e8bc3be7.jpg)
![Screenshot_20220529_120405_com jingdong app mall](https://user-images.githubusercontent.com/64320049/170851668-d66ee79c-f4f4-420e-ba03-10a435d1c4d4.jpg)
好像是因为无法自动同意协议授权手机号，所以导致任务假完成在这个页面卡死

**Comment by cibimo** [comment]
我也遇到了，还有一种情况是这个勾选框正好在左侧悬浮窗下面，程序也无法识别

**Comment by MonsterNone** [comment]
试着修复了一下，v17发布
