### ISSUE TITLE
喵币只会+100，被检测解决方法（需root）

### ISSUE THREAD

**Issue by cibimo** [MonsterNone/tmall-miao#214]
1.安装xposed模块“隐藏应用列表”，向淘宝隐藏所有与脚本/root有关的app（非必须？未测试）
2.在magisk中zygisk排除淘宝（非必须？未测试）
3.安装xposed模块“非残”，屏蔽淘宝无障碍检测（重要！）

**Comment by besty99** [comment]
跑了3个号，最后一个被检测了

**Comment by yezie** [comment]
那还是先手动好了。。

**Comment by MonsterNone** [comment]
我测试手机上不安装autojs，不安装其他辅助，不会被检测到

**Comment by MonsterNone** [comment]
还是感谢
