### ISSUE TITLE
执行京东任务出错，获取初始金币数量失败

### ISSUE THREAD

**Issue by Rothschild-hhu** [MonsterNone/tmall-miao#217]
非常感谢大佬提供如此方便的工具。今天早上把工具从11更新到13，执行京东任务时出错，报错信息如下：

> 获取初始金币数量
> 当前共有false金币
> 寻找为完成任务…
> 领取累计奖励
> 最后进行签到任务
> undefined[JavaException:java.lang.ArrayIndexOutOfBoundsException:length=2;index=2]

手机信息如下：

> OnePlus A3000
> Android 8.0.0
> 京东APP V11.02

曾使用2天的11版本，难道是被京东检测出来了？不知大佬有没有相应的解决措施，非常感谢，祝好！

![CH6(}~CVT7%I{@@9CB 9}}W](https://user-images.githubusercontent.com/58320451/170854576-f1fdd5ee-fba9-4d15-a8d5-e9e62b0ceaa6.jpg)

**Comment by MonsterNone** [comment]
你这个看着像哪里出错了，连任务也获取不到；要不重新运行或者重启手机试一下？V11->V13没有更新基础逻辑，应该不是版本的问题。

**Comment by Rothschild-hhu** [comment]
> 你这个看着像哪里出错了，连任务也获取不到；要不重新运行或者重启手机试一下？V11->V13没有更新基础逻辑，应该不是版本的问题。

好的，我试试重启手机，谢谢您。

**Comment by MonsterNone** [comment]
> > 你这个看着像哪里出错了，连任务也获取不到；要不重新运行或者重启手机试一下？V11->V13没有更新基础逻辑，应该不是版本的问题。
> 
> 好的，我试试重启手机，谢谢您。

不客气，如果还是不行的话reopen这个issue
