### ISSUE TITLE
抽奖问题三个

### ISSUE THREAD

**Issue by yezie** [MonsterNone/tmall-miao#218]
1. 做完任务后判断抽奖次数为0
2. 抽奖失败
3. 有时无法打开抽奖页面就直接结束了

**Comment by MonsterNone** [comment]
抽奖次数为0是因为这个店的任务之前已经做过了，另外两个问题确实偶尔会出现，有待研究修复

**Comment by yezie** [comment]
另外，在我的分红页底下有可抽奖品牌完整列表，共12个，从这里读取就不会一直循环

**Comment by OliCheung** [comment]
大佬 请问淘宝要用哪一个版本？

**Comment by MonsterNone** [comment]
> 大佬 请问淘宝要用哪一个版本？

最新版就行，如果手机里还有其他辅助只能用10.0以下版本
