### ISSUE TITLE
未能进入活动，请重新运行

### ISSUE THREAD

**Issue by lxl1374** [MonsterNone/tmall-miao#219]
我用的是红米note7，每次进去都显示超时，性能不行所以加载太慢？

**Comment by lxl1374** [comment]
我观察了一下在软件跳转活动的时候会白屏，卡最后一点，然后跳未能进入活动

**Comment by lionkingc** [comment]
未能进入活动的可以在任务开始前取消软件的第一个选项,,按开始后, 30秒内手工打开京东的活动任务列表

**Comment by MonsterNone** [comment]
如楼上，可以手动选一下。京东App无法打开任务页面的情况似乎和webview有关，检察一下你手机的webview版本，另外京东如果是google play版本最好换成小米商店版本。
