### ISSUE TITLE
淘宝浏览任务卡住问题

### ISSUE THREAD

**Issue by Javonne-do** [MonsterNone/tmall-miao#221]
![1483827817](https://user-images.githubusercontent.com/75659415/170987328-fd0c02bb-1359-4231-a187-1552ed5d006f.jpg)
卡在这里不返回
那个币的进度条还没走完就已经在寻找新的入口了
手机类型是：nova7se

**Comment by Javonne-do** [comment]
经过测试v13版本可以使用没有这个错误，v14版本会报这个错误

**Comment by MonsterNone** [comment]
V15发布之后你再试一下，如果还是有问题就reopen这个issue
