### ISSUE TITLE
淘宝任务，V14浏览店铺后不能返回，V13却正常

### ISSUE THREAD

**Issue by bilibili20001** [MonsterNone/tmall-miao#222]
Xperia XZ1，Android 9，Play版淘宝，webview已经降级
显示的“任务完成，返回”，实际却还在店铺界面
V14出现的问题，退回V13能正常使用
![Screenshot_20220531-003434](https://user-images.githubusercontent.com/70944645/171071476-a53f8609-82af-4380-81d8-2a5d7cf7a49e.png)

**Comment by MonsterNone** [comment]
V15/V16已修复，谢谢
