### ISSUE TITLE
V15版本的京东任务无法开始，提示无法找到人物列表控件

### ISSUE THREAD

**Issue by tunderbolt6** [MonsterNone/tmall-miao#224]
V14版本正常，V15就有这个问题
![image](https://user-images.githubusercontent.com/106567104/171075426-b691f858-aaec-4c60-bc7a-039421356235.png)

**Comment by neilzhengzx** [comment]
+1

**Comment by MonsterNone** [comment]
不同机型页面不太一样，V16已经修复
