### ISSUE TITLE
v14-v16淘宝判定返回逻辑有误，v13正常

### ISSUE THREAD

**Issue by rqnj** [MonsterNone/tmall-miao#225]
v14-v16进入淘宝任务后会直接判定为完成，v13没有问题
系统：MIUI13

**Comment by 975914892** [comment]
+1，小米11pro连打开淘宝任务都不能

**Comment by MonsterNone** [comment]
V16也不行吗？是什么手机？

**Comment by MonsterNone** [comment]
这里等待进入任务5秒之后才开始检测，如果手机5秒还没进入可能会判定完成 https://github.com/MonsterNone/tmall-miao/blob/c391a799c0af9e857135b4148496f258efc537c6/start.js#L154

**Comment by MonsterNone** [comment]
[59588e3](https://github.com/MonsterNone/tmall-miao/commit/59588e35056f5e07f2948e1d440e9cf677338626) 增加了更加严格的检测，随着V17一起发布

**Comment by rqnj** [comment]
> V16也不行吗？是什么手机？

k40
5秒之内已经进去了，不是这个问题
