### ISSUE TITLE
模拟器京东抽奖任务一直做不了。提示如下

### ISSUE THREAD

**Issue by nickolasgh** [MonsterNone/tmall-miao#226]
![Screenshot_20220531-102040](https://user-images.githubusercontent.com/35017933/171080023-490b5432-dd94-4d9e-a1ce-56fff1b3dd97.png)
逍遥模拟器，好几个帐号都不行。

**Comment by MonsterNone** [comment]
应该是模拟器控件不一样，之后研究一下

**Comment by nickolasgh** [comment]
大佬用的什么模拟器做测试？

**Comment by MonsterNone** [comment]
> 大佬用的什么模拟器做测试？

我也是用的逍遥，不过没有试过抽奖任务，我现在试一下

**Comment by lutherline** [comment]
双开应用抽奖任务也弹不出来
