### ISSUE TITLE
淘宝遇到这种进度条在右上角的就无法识别、返回了。

### ISSUE THREAD

**Issue by wusheng23** [MonsterNone/tmall-miao#228]
![IMG_20220531_110106](https://user-images.githubusercontent.com/102839384/171084631-96f8dd85-8118-4711-af0d-e0be1fba84af.jpg)
淘宝遇到这种进度条在右上角的就无法识别、返回了。

**Comment by MonsterNone** [comment]
检测有一个30秒的超时，未检测到标识会30秒自动返回，等一等就行了。不过这确实是个问题，什么原因造成的目前还没结论。
