### ISSUE TITLE
京东能用淘宝却不能用

### ISSUE THREAD

**Issue by 970844297** [MonsterNone/tmall-miao#231]
提示无法找到任务列表
![Screenshot_2022-05-31-23-52-44-848_com taobao taobao](https://user-images.githubusercontent.com/49755767/171217475-f0511057-361b-426a-8ff5-555eb9f48c95.jpg)

webview原来为88.xxx版，更新到100.0.4896.88后，淘宝仍不可用
淘宝为国内最新版，10.12.10
手机为小米mix2s，miui12
麻烦了，谢谢

**Comment by MonsterNone** [comment]
这个是新手教程没有完成，多点几下升级就好了

**Comment by 970844297** [comment]
似乎仍然无法使用

**Comment by 970844297** [comment]
![Uploading Screenshot_2022-06-01-23-44-21-218_com.taobao.taobao.jpg…]()
补图
