### ISSUE TITLE
jd “去玩游戏抢千万京豆”  脚本会卡住

### ISSUE THREAD

**Issue by bceyk** [MonsterNone/tmall-miao#233]
奇旅任务 “去玩游戏抢千万京豆” 
黑号进入 “集勋章赢千万京豆”后，返回自动到京东首页
此时脚本报错停止

**Comment by llyy390** [comment]
同样的情况，都这里就执行不下去了，看是否能跳过

**Comment by yezie** [comment]
+1 这里需要加语句判断任务名去跳过，jd以前也有过这样的情况，过两天任务就会恢复

**Comment by s1sunny** [comment]
一样卡住。

**Comment by yezie** [comment]
找到解决方法：跳转的瞬间马上按返回，就过了
