### ISSUE TITLE
京东能用淘宝却不能用(已过新手教程)

### ISSUE THREAD

**Issue by 970844297** [MonsterNone/tmall-miao#236]
提示无法找到任务列表
![Screenshot_2022-06-02-11-17-08-295_com taobao taobao](https://user-images.githubusercontent.com/49755767/171545757-79599f3b-e9b6-4d2f-93e8-641beb3d8429.jpg)
webview原来为88.xxx版，更新到100.0.4896.88后，淘宝仍不可用
已过新手教程
淘宝为国内最新版，10.12.10
手机为小米mix2s，miui12
麻烦了，谢谢

**Comment by Mading706** [comment]
同问，也碰到这个问题了

**Comment by MonsterNone** [comment]
先选手动打开任务列表吧，我去看看什么情况

**Comment by 970844297** [comment]
![Screenshot_2022-06-03-14-26-25-781_com taobao taobao](https://user-images.githubusercontent.com/49755767/171799168-4bddd7d7-e6cb-483c-9279-6edcb0e7d600.jpg)
情况相同

**Comment by 970844297** [comment]
![Screenshot_2022-06-03-14-28-05-796_com github MonsterNone](https://user-images.githubusercontent.com/49755767/171799355-f9ceedff-aa0e-4def-ac48-ead23f3c2b44.jpg)
设置应该没错
