### ISSUE TITLE
有些任务会触发弹出打开APP的界面，程序返回不了，必须手动点取消

### ISSUE THREAD

**Issue by hqw567** [MonsterNone/tmall-miao#237]
![Screenshot_2022-06-02-12-13-11-843_com miui securitycore](https://user-images.githubusercontent.com/74847198/171552284-67962d2d-f8d8-446e-936e-11a5317b43f3.jpg)

**Comment by MonsterNone** [comment]
可能是因为你有两个京喜

**Comment by hqw567** [comment]
薅羊毛,装2个不是标配?怎么能叫薅羊毛
