### ISSUE TITLE
淘宝活动结束之后无法自动领取奖励

### ISSUE THREAD

**Issue by touchren** [MonsterNone/tmall-miao#238]
原代码为: (2022618-17 的 270行)
            // 没有任务之后领取奖励
            var awardButtonFind = textMatches(/立即领取/)

在我手机上, 按钮显示为 "领取奖励" , 因此这样可以领取
            var awardButtonFind = textMatches(/立即领取|领取奖励/)

**Comment by MonsterNone** [comment]
去年的代码一直没改，已merge，谢谢
