### ISSUE TITLE
黑号了。。。

### ISSUE THREAD

**Issue by acm-py** [MonsterNone/tmall-miao#24]
现在升级奖励就一分，今天任务都给100-500喵币，有点自闭。。淘宝太不大气了。

**Comment by JunShine** [comment]
同是这样，用了脚本之后任务都是200猫币甚至没有。不知道这淘宝怎么做到的，识别后台程序？真NND

**Comment by cdlaimin** [comment]
autojs应该被识别了

**Comment by jzl2163** [comment]
同黑号，卸载后正常

**Comment by TernenceZhou** [comment]
> 同黑号，卸载后正常

卸载后重装淘宝，然后使用脚本正常？还是

**Comment by jzl2163** [comment]
> > 同黑号，卸载后正常
> 
> 卸载后重装淘宝，然后使用脚本正常？还是

卸载脚本后手动做任务正常

**Comment by JunShine** [comment]
也就是说脚本全费了没法用了，不知道可以改程序名或者阻止淘宝检测吗？

**Comment by wangyuxiang985** [comment]
> 也就是说脚本全费了没法用了，不知道可以改程序名或者阻止淘宝检测吗？

阻止淘宝检测应该不太现实吧，哈哈哈，估计是检测到auto.js了吧

**Comment by jzl2163** [comment]
> 也就是说脚本全费了没法用了，不知道可以改程序名或者阻止淘宝检测吗？

应该不是检查包名的，我关了淘宝查找本机应用的权限

**Comment by sunazl** [comment]
把无障碍关了就好了 不需要卸载

**Comment by liazylee** [comment]
有点难受，竟然没有分

**Comment by MonsterNone** [comment]
Duplicate of #27
