### ISSUE TITLE
感谢制作|关于京东任务反馈

### ISSUE THREAD

**Issue by TeslaLyon** [MonsterNone/tmall-miao#241]
在全部任务中间有个“去首页浮层进入活动” & “去组队份大奖” 的任务，会导致中断，需要手动执行后，再运行脚本完成后边的任务。
明天尝试着根据源码添加一下。

**Comment by MonsterNone** [comment]
这两任务`去完成`和`去领取`控件是一样的，不截图的情况下无法判断是完成还是领取，我目前还没想到方法来自动完成，如果你有好思路欢迎pr

**Comment by MonsterNone** [comment]
V20已经支持
