### ISSUE TITLE
京东有新任务-神秘徽章小站

### ISSUE THREAD

**Issue by exlife1** [MonsterNone/tmall-miao#242]
位置：我的奖励  拉到最下面  有京豆还有金币奖励，希望作者能更新谢谢！

**Comment by MonsterNone** [comment]
收到，之后看下什么情况

**Comment by MonsterNone** [comment]
徽章我发现只要点几下就能全收集了，暂时不添加自动完成

**Comment by exlife1** [comment]
![image](https://user-images.githubusercontent.com/47602062/173170002-c79ed27f-90d3-48ab-a39d-9a59c7c72d0d.png)
![image](https://user-images.githubusercontent.com/47602062/173170007-1e801b37-d8e0-4946-8228-4077d4142e6e.png)
每个店铺都有四五个任务，做任务获得掷骰子机会，掷骰子以后可以获得金币、京豆。不是点几下就能完成的
