### ISSUE TITLE
淘宝问题反馈

### ISSUE THREAD

**Issue by bxmydt** [MonsterNone/tmall-miao#245]
点击开始淘宝任务后，如果在任务设置里取消勾选自动打开淘宝进入活动，会提示”“取消选择，任务停止“。京东任务则不会有这个问题。

**Comment by MonsterNone** [comment]
发现是两个都取消勾选之后有问题，下个版本修复，谢谢

**Comment by bxmydt** [comment]
> 发现是两个都取消勾选之后有问题，下个版本修复，谢谢

麻烦您了麻烦您了，非常抱歉因为偷懒没有上截图，感谢您的耐心

**Comment by MonsterNone** [comment]
> > 发现是两个都取消勾选之后有问题，下个版本修复，谢谢
> 
> 麻烦您了麻烦您了，非常抱歉因为偷懒没有上截图，感谢您的耐心

不客气，[455a7aa](https://github.com/MonsterNone/tmall-miao/commit/455a7aa3514af089c4c101b942dc21022920489d)已修复，V19一起发
