### ISSUE TITLE
你们最近分红拿多少？似乎有点异常

### ISSUE THREAD

**Issue by shadowfish07** [MonsterNone/tmall-miao#251]
天天用这个刷，分红到280的时候，连续出两次5...还是换了季节刷的

**Comment by MonsterNone** [comment]
异常一般是金币变少，分红不会出现问题

**Comment by yezie** [comment]
我都满级了，分红只有255，最后一级也只有5，别人都30

**Comment by google-mirror** [comment]
是的, 最近都黑号了, 分红195每次也就5分红

**Comment by w-gitc** [comment]
https://tieba.baidu.com/p/7873481073

**Comment by w-gitc** [comment]
https://tieba.baidu.com/p/7873481073
https://tieba.baidu.com/p/7878105384

有可能是被检测到是刷的 不阻止但降低奖励，也可能就是杀熟 黑号。
