### ISSUE TITLE
京东任务执行过程中多次报错停止

### ISSUE THREAD

**Issue by tunderbolt6** [MonsterNone/tmall-miao#254]
v19版本运行无异常，更新到V20后有报错。
报错如下图所示，K40pro  miui13.0.6

![Screenshot_2022-06-14-16-06-11-729_com jingdong a](https://user-images.githubusercontent.com/106567104/173527381-5f13d347-9ef6-4378-885c-52b1adeda02d.jpg)

**Comment by MonsterNone** [comment]
我暂时还没能遇到这个问题，你先继续用V19吧。有可能是无障碍权限的问题，重启手机试试看
