### ISSUE TITLE
请问作者如何打包防止淘宝检测？

### ISSUE THREAD

**Issue by Jefferyanna** [MonsterNone/tmall-miao#255]
我在学习制作辅助，正好最近在使用这款618辅助，看到你使用了全新的打包方式防止淘宝检测无障碍！我最近也碰到了别的APP有类似的检测，想请教一下！

**Comment by MonsterNone** [comment]
看一下这个#106

**Comment by MonsterNone** [comment]
Duplicate of #106

**Comment by Jefferyanna** [comment]
请问能分享下具体步骤吗？不太会操作，自己尝试替换之后没有成功。请问能分享下具体步骤吗？使用哪些软件、方法之类的，感谢！
