### ISSUE TITLE
京东的任务建议增加随机延迟

### ISSUE THREAD

**Issue by atest1** [MonsterNone/tmall-miao#258]
我跑脚本到最后抽奖只有5份了（应该是30份的），惨惨惨
不知道有没有类似的情况的
现在怀疑是京东检测了是否是用脚本运行的，人工点的话必然有不同的延迟，所以建议增加一个延迟

**Comment by bxmydt** [comment]
好家伙，我还以为是京东只给5份了呢😂

**Comment by MonsterNone** [comment]
5份问题看#251 ，现在脚本流程里其实已经有延迟了；另外我猜测检测和点击延时无关，网络波动、时钟同步都可能导致延迟检测失败
