### ISSUE TITLE
小米10u 打开弹窗权限了  但是 还是显示 没有权限   也信任了该应用 

### ISSUE THREAD

**Issue by liaopen123** [MonsterNone/tmall-miao#267]
![Screenshot_20221020_111324.png](https://pic.jitudisk.com/public/2022/10/19/9b2e2a032b7bd.png)
![Screenshot_20221020_111217.png](https://pic.jitudisk.com/public/2022/10/19/63092a591b7be.png)
小米10u 打开弹窗权限了  但是 还是显示 没有权限

**Comment by MonsterNone** [comment]
抱歉，你的图片似乎无法显示。

弹窗主要是用来显示软件运行状态和日志，取消了弹窗会造成比较大的麻烦，暂不能取消。

**Comment by liaopen123** [comment]
> 抱歉，你的图片似乎无法显示。
> 
> 弹窗主要是用来显示软件运行状态和日志，取消了弹窗会造成比较大的麻烦，暂不能取消。

好了    我更新截图了。华为的没问题 就是小米的这个   我点击2 悬浮窗   然后就跳到悬浮窗的界面 提示我 没有权限

**Comment by kaikidd** [comment]
小米11遇到同样的问题

**Comment by MonsterNone** [comment]
重启手机试一下？我用k30没有复现出这个问题

**Comment by kaikidd** [comment]
![WechatIMG327](https://user-images.githubusercontent.com/32085026/196938733-8d7e3e86-62b8-4aaf-9850-92f6ac08cbf1.jpeg)
重启试了不行
MIUI 13.0.9

**Comment by liaopen123** [comment]
> 重启手机试一下？我用k30没有复现出这个问题

哈哈 我重启  重装  打开了 关    各种操作都不好使   眉有办法

**Comment by MonsterNone** [comment]
这倒是也奇怪了😂我的13.0.6复现不出此问题

**Comment by liaopen123** [comment]
解决办法 换个手机 [狗头]
