### ISSUE TITLE
去年双十一搞了多少，各位？

### ISSUE THREAD

**Issue by cy920820** [MonsterNone/tmall-miao#268]
感觉一年比一年少，10 块都不到了吧

**Comment by cy920820** [comment]
电费都不止了  🤣

**Comment by MonsterNone** [comment]
这倒不至于吧🤣618我没升满级大概20多，满级有50

**Comment by tangguangliang** [comment]
618 我也没升满，有40左右，我老婆接近50

**Comment by cy920820** [comment]
> 这倒不至于吧🤣618我没升满级大概20多，满级有50

我确实没到 10 块钱红包，😅

**Comment by MonsterNone** [comment]
> 我确实没到 10 块钱红包，sweat_smile

是不是被判定黑号？

**Comment by usedlife** [comment]
费心费力地玩，50左右
