### ISSUE TITLE
黑号(每次只有100喵币)的亲们,可以尝试把无障碍关了

### ISSUE THREAD

**Issue by sunazl** [MonsterNone/tmall-miao#27]
rt

**Comment by xuyuwei1801220021** [comment]
无障碍关了就不能用了啊？

**Comment by sunazl** [comment]
> 无障碍关了就不能用了啊？

那没办法啊  手动呗

**Comment by MonsterNone** [comment]
根据[这篇帖子](https://www.52pojie.cn/thread-1289675-1-1.html) ，安装淘宝9.0版本可以应对检测。

链接贴上[豌豆荚 - 淘宝9.0版](https://www.wandoujia.com/apps/32267/history_v253)
