### ISSUE TITLE
反馈2个活动bug

### ISSUE THREAD

**Issue by happy4041** [MonsterNone/tmall-miao#271]
### 第1个：有几率遇到入会卡在这里重复循环入会失败。只见到弹出授权手机号，打了钩，然后没有成功授权入会。
![image](https://user-images.githubusercontent.com/19932220/196870190-c3daa5e5-35c2-4fdd-b1b0-1cbc9e790dee.png)

### 第2个：所有任务刷完了，就剩这个去逛逛并下单的任务，导致无限循环，永远结束不了任务。
![image](https://user-images.githubusercontent.com/19932220/196870335-f51d8d47-a1e4-4d37-b125-ffbb7eaea302.png)
![image](https://user-images.githubusercontent.com/19932220/196870374-90795c0c-01ef-4fbf-a8e2-54592f7b4acc.png)

暂时就以上两个bug反馈，剩下的麻烦您了！

**Comment by zhiao6** [comment]
建议多增加几个选择不执行的任务

**Comment by MonsterNone** [comment]
感谢，V3、V4修复了这2个问题
