### ISSUE TITLE
[Proposal] 微信京东小程序支持

### ISSUE THREAD

**Issue by eebssk1** [MonsterNone/tmall-miao#273]
微信的京东小程序可以额外进行任务领金币。不知道有没有计划加入支持。

**Comment by hiCasper** [comment]
目前似乎小程序判断逻辑是安装了微信，点击按钮就算完成，应该无需做后续判断

**Comment by eebssk1** [comment]
> 目前似乎小程序判断逻辑是安装了微信，点击按钮就算完成，应该无需做后续判断

点前往微信的图片可以领。微信里的京东任务是分开的，可以同时做
