### ISSUE TITLE
未能打开任务列表，请关闭京东重新运行

### ISSUE THREAD

**Issue by lionkingc** [MonsterNone/tmall-miao#274]
夜神模拟器, 手工打开任务列表可以做部份任务
但是遇到需要由<自动化软件>关闭任务列表再打开时, 就会出错, 无法自动打开任务列表 

function openTaskList() {
    console.log('打开任务列表')
    let taskListButtons = descMatches(/.*解锁.*还需.*/).clickable().findOne(20000)

场景都解开了,感觉没再看到这句  '解锁 XXX 还需XXX ' 这句话呀, 现在只有 "距离下次抽到分红\n 还需x 次"

![Screenshot_20221020-174051](https://user-images.githubusercontent.com/23330617/196914645-468fa809-1db6-4029-868d-b596591654be.png)

**Comment by MonsterNone** [comment]
v2之后的版本都更新了，升级试一下

**Comment by lionkingc** [comment]
用上了最新的v4版本, 一样情况.

![Screenshot_20221020-235431](https://user-images.githubusercontent.com/23330617/196998456-655fefc9-7e03-4b84-8770-a455897753a2.png)

**Comment by duanhunxue** [comment]
大佬~我也是这个情况。
机型：mate 30 pro 。
系统：鸿蒙2.0
问题：未能打开任务列表，自动退出。

**Comment by sundys** [comment]
小米9昨天运行可以,今天也是这个提示,把2个APP数据全部清除重装也是这个提示

**Comment by MonsterNone** [comment]
@lionkingc 或许你调整模拟器的分辨率试试？我看着抽奖控件在屏幕上显示不全

**Comment by duanhunxue** [comment]
> > 大佬~我也是这个情况。 机型：mate 30 pro 。 系统：鸿蒙2.0 问题：未能打开任务列表，自动退出。
> 
> 日志麻烦截图看一下GUOJI(
#
![miss](https://user-images.githubusercontent.com/102618138/197093143-237d8935-ad0e-4fdc-a657-69b8858cfcb1.jpg)

**Comment by MonsterNone** [comment]
> 

PRO版似乎不支持京东APP的相关操作，模拟器问题我这边测试一下吧。有些用户反馈能正常运行，有些就不行。

**Comment by MonsterNone** [comment]
@duanhunxue 你这个可能需要在软件运行识别任务列表的时候手动点一下抽奖

**Comment by lionkingc** [comment]
试了V5,能划动, 但是没找到控件.

![Screenshot_20221021-120837](https://user-images.githubusercontent.com/23330617/197109852-a9825135-4039-41fd-87ee-e265159acf71.png)

**Comment by 357283670** [comment]
大佬，手持洋垃圾索尼的用户反馈，虽然也碰上这个问题，但是已经手动解决了，不知道他们能不能测试一下。原因是打开脚本后有个打开jd然后再拉出活动的过程，这个过程因配置不同导致载入速度巨慢。等页面打开，脚本也因为超时停止了。建议你们跟我一样，先打开活动界面，然后启动脚本，这时候会切换到jd，然后它再次在活动界面拉活动界面（重点：这时候按返回，让他不再拉取新的活动界面，）这时候他会判定你已经进入活动，然后就可以正常跑了。如果都是这个问题，可以考虑让大佬改改逻辑。顺便支持大佬的辛勤成果

**Comment by lionkingc** [comment]
@MonsterNone  你好.  v7版本的 start_jd.js 有同步更新吗, 

目前只能装AUTOJS 然后把这个JS里的打开任务列表和关闭任务列表里的代码删除, 然后手工打开任务列表 , 可以做任务.

**Comment by MonsterNone** [comment]
@lionkingc 有的，在main分支里

**Comment by lionkingc** [comment]
> @lionkingc 有的，在main分支里

喜大普奔, 终于可以了, 试了好几天, 谢谢作者

最大的原因在于本人是多开, 导致网络有些延迟,
在610行scrollDown();后面加入sleep(5000) 后一切正常, 能正常打开活动菜单了
之前虽然  '成功进入活动，向下滑动一段以保证控件全部出现'   但速度太快了, 立马执行了openTaskList(); 导致失败.

**Comment by MonsterNone** [comment]
@lionkingc 诶？？有点奇怪，理论上openTaskList()都有个`let taskListButtons = text('消耗').findOne(20000)`，在这个里面会等待20秒寻找`消耗`(就是抽奖按钮)

**Comment by lionkingc** [comment]
当时测试的时候, 下滑后 ,taskListButtons 是true的, 但是试了加上个click()没反应 , 不太懂这些原理 ,我以为能试下让他点<抽奖>,如果不行

**Comment by MonsterNone** [comment]
https://github.com/MonsterNone/tmall-miao/blob/main/start_jd.js#L163
这里你把它改成（就是点击两次）
```
taskListButton.click()
sleep(5000)
taskListButton.click()
```
试试呢？

**Comment by lionkingc** [comment]
> https://github.com/MonsterNone/tmall-miao/blob/main/start_jd.js#L163 这里你把它改成（就是点击两次）
> 
> ```
> taskListButton.click()
> sleep(5000)
> taskListButton.click()
> ```
> 
> 试试呢？ @lionkingc
> 
> 我想起来618版本的时候也有类似问题，后来是加上模拟点击座标才解决了，似乎和webview有关

618的时候有些版本好像也有这个问题, 忘记当时哪个版本就解决好了的.

> taskListButton.click()
sleep(5000)
taskListButton.click()

这块也试了几次, 都不行,  反而在        scrollDown();后面 加		sleep(5000)
就顺利解决了

**Comment by lionkingc** [comment]
对了, 入会那也有个小BUG, 几天之前的版本不会, 这几次更新的反而会了.
就是某些入会时, 已经能获取到我的手机号, 只需要点那个红点,然后点确认就能加了,
这时浮窗会闪过一大段代码, 然后JD页面也变成需要手工输入手机号和验证码状态 .

今天的都做完了,等明天找机会截图发上来你看看

**Comment by lionkingc** [comment]
![Screenshot_20221025-093541](https://user-images.githubusercontent.com/23330617/197661720-7989d726-a182-48fa-a9c9-1dc5fb030738.png)


如图, 原本是有手机号的,只需要确定就能加入, 后面程序点错了位置 ,变成了需要重新 输入 手机号+ 验证码了

**Comment by MonsterNone** [comment]
我这里试了下漫步者旗舰店，没能复现

**Comment by lionkingc** [comment]
> 我这里试了下漫步者旗舰店，没能复现

不用特定哪家店, 随便一家还没开过会员的就可以,

**Comment by MonsterNone** [comment]
@lionkingc 麻烦你看一下确认授权前面的选择按钮，在手机号控件的后面第几个？

目前确认授权勾选的匹配方式是，问题应该出在`indexInParent() + 2`上
```
let anchor = textContains('*****').findOnce()
check = anchor.parent().child(anchor.indexInParent() + 2)
```

**Comment by MonsterNone** [comment]
@lionkingc 增加了一种备用方法，6ba79cd。

如果这个方法还是不行说明页面控件差异比较大，我之后安装夜神模拟器试试

**Comment by lionkingc** [comment]
> @lionkingc 增加了一种备用方法 [6ba79cd](https://github.com/MonsterNone/tmall-miao/commit/6ba79cdf9fbda7f0fbfa65fe457d189a6875decd)
> 
> 如果这个方法还是不行说明页面控件差异比较大，我之后安装夜神模拟器试试

目前想复现比较难找到, 因为多数任务已经加入过会员了,就不会出现这种框, 遇到的时候悬浮窗上的那串代码一闪而过,过几秒后就会返回到主任务界面, 该商家也会被自动刷新换成别的商家, 因此不会陷入无限循环中

一会我试试你这个备用方法再来反馈
