### ISSUE TITLE
有一些入会任务检测入会授权按钮

### ISSUE THREAD

**Issue by NNanfeng** [MonsterNone/tmall-miao#276]
如题
手机是redmi K30Pro 5G
MIUI 13.0.1

**Comment by NNanfeng** [comment]
![Screenshot_2022-10-20-21-58-39-359_com jingdong a](https://user-images.githubusercontent.com/92158315/196970417-e272de26-59b5-4326-a300-7cc5abfc2d5d.jpg)

**Comment by MonsterNone** [comment]
0e2ded15bd90a3707a393f5413e10586c8b2dc46
