### ISSUE TITLE
模拟滑动失效 v4

### ISSUE THREAD

**Issue by zj312** [MonsterNone/tmall-miao#277]
Redmi k40, Redmi note 9  
目前发现有一个浏览任务，模拟滑动后未开始8秒倒计时，导致一直卡在这个任务，建议是不是可以把滑动的幅度调大一点

**Comment by MonsterNone** [comment]
V5 将会调整成
```
从(device.width / 2, device.height - 200)滑动到(device.width / 2 + 20, device.height - 500)，时长 1000ms
```
不知道这样会不会好一点。我本地K30测试是能触发的

**Comment by ZengJun-cloud** [comment]
> V5 将会调整成
> 
> ```
> 从(device.width / 2, device.height - 200)滑动到(device.width / 2 + 20, device.height - 500)，时长 1000ms
> ```
> 
> 不知道这样会不会好一点。我本地K30测试是能触发的

我这个k30s也发现滑动幅度小了一点，有时候任务没有完成。

**Comment by 357283670** [comment]
应该说的那个共6个任务 浏览8秒给7000金币的任务。因为我的机子内存小，我的提示进度条出的特别慢，可能已经滑动过了进度条才读出来，导致无法触发。而且我发现这个任务左上角的（start_jd里）就没有第一个成功的模拟滑动的提示。破手机安卓8.0索尼3g内存小手机。

**Comment by MonsterNone** [comment]
@357283670  日志里不会提示模拟滑动成功与否(一般都是成功的)，另外滑动是在检测到进度条之后才会开始滑动。

V5里面增加了一个1s的延时，V5能正常滑动并检测吗？

**Comment by MonsterNone** [comment]
各位方便的话可以在手机的开发者选项里面打开`显示点按操作反馈`，看看是滑动行程还是滑动时机问题

**Comment by 357283670** [comment]
@MonsterNone 好的大佬，我考虑毕竟我的手机已经属于淘汰货了，经测试其他朋友的华为nova 5p 还有千元联想青春z6都可以一跑到底，大家如果都没问题，我这也就属于鸡蛋里挑骨头了。大家反映的问题，应该都是旧手机载入时间不同，导致的检测不到进度条然后导致失败，另外大佬能提供一个邮箱吗？我可以把发现的问题拍成小视频，要不然截图不够直观提现代码判定情况。

**Comment by MonsterNone** [comment]
@357283670 你的问题主要是由于目前设置的任务条检测时间10s，页面还没加载出来就检测结束了。设置的模拟滑动在检测到任务条之后才会触发。

V7改一下这个情况。

**Comment by 357283670** [comment]
@MonsterNone 现在模拟滑动的问题已经全部解决，剩下的就是我进入活动的判定问题了。
我找了个临时存储，你方便的时候看看，这个改动优先级不是很高，因为只会在最开始进入活动的时候手动操作，不会在中间停顿造成影响。
https://musetransfer.com/s/yr503spvt（有效期至10月29日）｜【Muse】你有一份文件待查收，请点击链接获取文件

**Comment by MonsterNone** [comment]
@357283670 ~~看到你视频的第一眼我就想起了被垃圾网络支配的恐怖，虽然咱俩原因不一样但是结果是一样的~~ 

我看之后要不然加一个全局等待时间设置的功能。

**Comment by 357283670** [comment]
@MonsterNone 感谢大佬细心看我每一个回复，希望我提供的这些毛病能让大佬的作品更完善。这些洋垃圾都是当时刚工作，用来给非漫游套餐的手机卡接电话用的。但我有个问题不解，这配置（晓龙820+3g运存）为什么打开一个京东的网页能如此的不流畅，大佬有没有同样毛病的旧手机给说点提速经验。

**Comment by MonsterNone** [comment]
@357283670 也谢谢你一直能提出问题（要不然我还发现不了哈哈）。我没有类似的设备，但是有位朋友用的`华为畅享7`，`EMUI 5`版本，据他所说一点都不卡，甚至还能开7个分身，我惊呆了。。。

**Comment by 357283670** [comment]
![IMG_9976](https://user-images.githubusercontent.com/81951825/197390783-d701c1a5-669b-4453-8bd2-a22064b54627.JPG)
因为我的浏览器也有一样的毛病，特别卡。我看了一下你别的issuse写的可能跟webview有关，我这个默认的是停用的。
