### ISSUE TITLE
打开任务列表失败

### ISSUE THREAD

**Issue by Luvletter01** [MonsterNone/tmall-miao#278]
机型：红米K50
错误：打不开任务列表，多次尝试未果
![Screenshot_2022-10-21-11-07-37-313_com jingdong app mall](https://user-images.githubusercontent.com/77605961/197102403-7cae4539-8540-4459-9c90-f100280dd5e9.jpg)

**Comment by MonsterNone** [comment]
系统应用里，webview的版本看一下。101及以上无法获取到控件，建议卸载更新。

**Comment by sweetasaki** [comment]
> 系统应用里，webview的版本看一下。101及以上无法获取到控件，建议卸载更新。

我的webview版本号是95.0.4638.74 ，也是无法打开任务列表。同K50，问题和截图一样

**Comment by sdjnr2012** [comment]
下午还好好的，晚上突然就打不开任务列表了，华为和小米手机都这样...

**Comment by sdjnr2012** [comment]
更新了版本好了...
