### ISSUE TITLE
这次京东穿越双十一做的很好了，一直有2个缺憾的地方。

### ISSUE THREAD

**Issue by SkyDanlog** [MonsterNone/tmall-miao#280]
一，京东双十一抽奖，大大还没开发。上传618的时候后期版本才加上了这个功能。
二，京东图鉴探索中到图鉴墙的扔骰子的功能，从以前几个版本看一直没加上。
      老大你是不是可以单独搞一个，由用户点出图鉴墙后，运行自动点击扔骰子

![jdtq](https://user-images.githubusercontent.com/106414653/197115244-be05b459-a19e-4ba0-9b9a-d60a0610126e.png)

**Comment by kinglear216** [comment]
你说的抽奖，是活动中的金币抽奖吗

**Comment by MonsterNone** [comment]
谢谢。抽奖这几天会加上，扔骰子后续考虑一下是否添加（感觉奖励太少，且活动在小程序里，加载比较卡顿）
