### ISSUE TITLE
未找到金币控件，并且报错

### ISSUE THREAD

**Issue by DDDHL** [MonsterNone/tmall-miao#281]
![image](https://user-images.githubusercontent.com/71803866/197197969-ce429c20-c205-4029-9445-ae4c2ffbe358.png)

**Comment by sclodestar** [comment]
应该是上滑导致的。

**Comment by MonsterNone** [comment]
上面条的“去领取”领取之后试试呢

**Comment by gzmars** [comment]
确实与领取累计的金币有关，手动领取后就正常运行了。
与分辨率无关，我从720改到1080还是报错，手动领取累积的金币后就正常了。

**Comment by MonsterNone** [comment]
> 确实与领取累计的金币有关，手动领取后就正常运行了。 与分辨率无关，我从720改到1080还是报错，手动领取累积的金币后就正常了。

感觉和机型也有关系，我这里几台设备的`去领取`控件标识的text属性都是`去领取去领取`，所以我对`任务列表`里的按钮正则限定为`^去领取$`匹配首尾，理论上能直接排除`累计奖励`的`去领取`按钮。

另外G版增加了对元素indexInParent的判断，可能能排除一些问题。
