### ISSUE TITLE
11.v06（F版出错，无法运行，之前的版本都没报错的）

### ISSUE THREAD

**Issue by gzmars** [MonsterNone/tmall-miao#284]
逍遥模拟器，助手升级到最新版本后报错。
![image](https://user-images.githubusercontent.com/46783444/197311510-703a9069-7b05-4ec5-9020-41fd45fe8a4e.png)

**Comment by MonsterNone** [comment]
可能是累计任务奖励的“去领取”造成的冲突，把去领取领了试试看

**Comment by MonsterNone** [comment]
Duplicate of #281 
请到281讨论
