### ISSUE TITLE
主app一直都是找不到任务,分身倒是确没有任何问题

### ISSUE THREAD

**Issue by ylh741** [MonsterNone/tmall-miao#287]
![QQ截图20221022170826](https://user-images.githubusercontent.com/32968639/197331449-21b9d1a3-5871-4b41-9f0b-4b3ed7a00915.jpg)
其他的几个分身都没这问题,就是主应用从一开始到现在的F版一直是这样

**Comment by MonsterNone** [comment]
我感觉和webview的版本有关，你检查一下应用列表里webview的版本

**Comment by ylh741** [comment]
![QQ截图20221022191410](https://user-images.githubusercontent.com/32968639/197336061-7c44c55c-fe9a-47e3-bccf-67be618715d2.jpg)

**Comment by MonsterNone** [comment]
@ylh741 卸载更新，webview101以下才能正常运行
