### ISSUE TITLE
v7-v8 都有淘宝任务返回错误

### ISSUE THREAD

**Issue by tangguangliang** [MonsterNone/tmall-miao#288]
![微信图片_20221023101304](https://user-images.githubusercontent.com/33145940/197369800-ef978f40-ed37-4837-9da0-6e9d89abd563.jpg)
报错截图

**Comment by tangguangliang** [comment]
手机型号：华为nova6

**Comment by MonsterNone** [comment]
有一个参数忘记取消了T_T 谢谢！下个版本修复。

**Comment by number2021620** [comment]
V7 V8在华为mate9 鸿蒙2上模拟滑动有问题

**Comment by number2021620** [comment]
影响不大，手动划一下解决

**Comment by number2021620** [comment]
老旧手机问题太古怪了

**Comment by MonsterNone** [comment]
@number2021620 是淘宝还是京东？

**Comment by 357283670** [comment]
@MonsterNone 哈哈哈，是淘宝。昨天手贱手点过去了，忘了也发出来。

**Comment by MonsterNone** [comment]
@357283670 V9版本和京东一样，加上了持续滑动

**Comment by tangguangliang** [comment]
更新v9版本后目前使用正常，大佬V5
