### ISSUE TITLE
关闭不了任务列表

### ISSUE THREAD

**Issue by ywz98280** [MonsterNone/tmall-miao#290]
做几个任务之后就关闭不了任务列表最后完全卡住列表，建议每做完一个任务都刷新一次就完美了，其他都挺好的就差每做完一个任务刷新列表这样就不会卡住了

**Comment by MonsterNone** [comment]
抱歉没能理解。麻烦具体描述一下，谢谢！

**Comment by MonsterNone** [comment]
目前是做完同类任务之后关闭任务列表重新打开，目的是为了让任务列表的控件元素刷新
