### ISSUE TITLE
淘宝能量店铺任务滑动失败

### ISSUE THREAD

**Issue by snake125023** [MonsterNone/tmall-miao#293]
使用雷电模拟器，升级到最新版，淘宝能量店铺任务滑动还是失败，卡在“15个商品数量不足”下滑 下滑 就结束了。

**Comment by eebssk1** [comment]
+1

**Comment by fengchun81969** [comment]
我也是的，我也用的雷电，而且京东任务做不了

**Comment by MonsterNone** [comment]
3cd5da6c699ac91b765a9a2695e70cc893ff4352
V10已修复
