### ISSUE TITLE
小米12x 淘宝 能量红包任务  浏览15个商品，一直报商品数量不足。

### ISSUE THREAD

**Issue by Gmle7** [MonsterNone/tmall-miao#296]
![f32dc7455603f4fe457be1a7de78f2a](https://user-images.githubusercontent.com/24665995/197508113-951cda9c-6223-46df-99a7-6c3ab32b1c14.jpg)

**Comment by zzw19921212** [comment]
我也是

**Comment by 1026644752** [comment]
我也是显示 商品数量不足 软件就停止运行了

**Comment by Hopkin23** [comment]
我也是，应该跟手机型号没关系，确实有这问题

**Comment by MonsterNone** [comment]
3cd5da6c699ac91b765a9a2695e70cc893ff4352 
V10已修复
