### ISSUE TITLE
京东活动bug

### ISSUE THREAD

**Issue by 1592363624** [MonsterNone/tmall-miao#301]
随便一个活动不是有分享+5000金币吗
然后点击分享，他会生成长图，这个时候切到后台，可能他就是检测窗口有没有切出去
再进来，就显示了+金币，而且下面的金币数字确实增加了
不过也不知道会不会有事。
因为以前没玩过活动，今年是看到这个软件跑进来凑热闹的
纯属是对软件的兴趣
对活动规则不太了解

[
![58C73CBE3B941C38FE0876749A1400FB](https://user-images.githubusercontent.com/50036597/197661899-6b2f60ee-c1c3-43cb-a120-d13ec3d17dd6.jpg)
![5ADAE866C387B41648A1F51531A5033C](https://user-images.githubusercontent.com/50036597/197661912-3682c6e7-cc0a-4964-9909-7f106369f8d8.jpg)
![3741BB6367DD88748653007CD7B29A56](https://user-images.githubusercontent.com/50036597/197661918-2cb05387-7cd6-4980-a6de-f4e9c66bcd7b.jpg)
![32A447C6B5FC0CAE45CFA1626750CBD6](https://user-images.githubusercontent.com/50036597/197661921-cbaa056b-8a78-4770-a78c-acf9eef7b173.jpg)
](url)

**Comment by MonsterNone** [comment]
京东程序员：扣钱！

**Comment by 1592363624** [comment]
> 京东程序员：扣钱！

我最主要的忘记说了，这个不是想说可以骗他我分享了，而是点了取消，然后又点分享，重复操作，这个界面可以一直刷。

**Comment by 1592363624** [comment]
> 京东程序员：扣钱！

我最主要的忘记说了，这个不是想说可以骗他我分享了，而是点了取消，然后又点分享，重复操作，这个界面可以一直刷，刚才试了一下，金币也可以增加

**Comment by 145535454** [comment]
![image](https://user-images.githubusercontent.com/108472427/197803053-6c14bd82-a01a-4431-8119-d01483146673.jpeg)大神救命
