### ISSUE TITLE
JD不能用了  好像已经无法打开任务列表

### ISSUE THREAD

**Issue by supercj** [MonsterNone/tmall-miao#302]

**Comment by MonsterNone** [comment]
麻烦截图，并说明手机型号、软件版本，谢谢

**Comment by zxccong** [comment]
![image](https://user-images.githubusercontent.com/44158259/197673864-8dec0a56-4d99-4e39-9160-09b42523597e.png)
你好，由于所有场景解锁了，代码第150行”descMatches(/.*解锁.*还需./)“ 无法找到控件，希望解决一下。

**Comment by Pikarziur** [comment]
> ![image](https://user-images.githubusercontent.com/44158259/197673864-8dec0a56-4d99-4e39-9160-09b42523597e.png) 你好，由于所有场景解锁了，代码第150行”descMatches(/.*解锁.*还需./)“ 无法找到控件，希望解决一下。

改一下就可以了，/.*解锁.*还需.*|.*份.*/

**Comment by zxccong** [comment]
图片上已经没有解锁两个字了亲

> > ![image](https://user-images.githubusercontent.com/44158259/197673864-8dec0a56-4d99-4e39-9160-09b42523597e.png) 你好，由于所有场景解锁了，代码第150行”descMatches(/.*解锁.*还需./)“ 无法找到控件，希望解决一下。
> 
> 改一下就可以了，/.*解锁._还需._|._份._/

图片上看看，已经没有解锁两个字了，正则改过了，不行的

**Comment by 357283670** [comment]
哥们作者都更新10几个版本了，你这还是首发版本，赶紧更新吧。

**Comment by Pikarziur** [comment]
> 图片上已经没有解锁两个字了亲
> 
> > > ![image](https://user-images.githubusercontent.com/44158259/197673864-8dec0a56-4d99-4e39-9160-09b42523597e.png) 你好，由于所有场景解锁了，代码第150行”descMatches(/.*解锁.*还需./)“ 无法找到控件，希望解决一下。
> > 
> > 
> > 改一下就可以了，/.*解锁._还需._|._份._/
> 
> 图片上看看，已经没有解锁两个字了，正则改过了，不行的

你没有留意到我用的是  | 或     ， 为的是同时解决了未开启四个场景和开了四个的

**Comment by MonsterNone** [comment]
对，用mian分支的。
现在是`text('消耗')`
