### ISSUE TITLE
夜神模拟器滑块验证过不去

### ISSUE THREAD

**Issue by DreamDreamer** [MonsterNone/tmall-miao#303]
### 配置机型
- 夜神模拟器
- 安卓7
- 机型设置Redmi

![Screenshot_20221025-103705](https://user-images.githubusercontent.com/6091242/197669869-8a43a266-0ea1-44dc-a913-9ee6b207994e.png)

**Comment by lionkingc** [comment]
一样夜神 , 一样情况

**Comment by MonsterNone** [comment]
淘宝最好不要用模拟器，容易黑
