### ISSUE TITLE
模拟器运行喵果总动员报错

### ISSUE THREAD

**Issue by raoji6** [MonsterNone/tmall-miao#305]
![image](https://user-images.githubusercontent.com/34682460/197675027-89dcfb44-2174-4846-8dc9-bff9136060fd.png)

**Comment by AN-535** [comment]
![_~8 FSKIZ2)187MS7`G1A50](https://user-images.githubusercontent.com/33016525/197676968-bdfdd34b-58eb-41af-9a13-4e24a4085544.png)
模拟器安卓9，一样的问题

**Comment by raoji6** [comment]
淘宝升级最新版可以解决

**Comment by raoji6** [comment]
或者试试逍遥模拟器

**Comment by Eyion** [comment]
类似的报错
模拟器版本：雷电模拟器9.0.26（9）
淘宝版本：10.17.0
Autojs脚本版本：V12
![image](https://user-images.githubusercontent.com/26318038/197681283-11da9b09-e369-4b62-8c98-acc47f82e5ac.png)

**Comment by AN-535** [comment]
> 或者试试逍遥模拟器

![image](https://user-images.githubusercontent.com/33016525/197698801-62f4f30b-ae03-4a16-8973-369e17cd328e.png)
换了逍遥模拟器，一直卡在第一个任务

**Comment by lionkingc** [comment]
![Screenshot_20221025-141621](https://user-images.githubusercontent.com/23330617/197699054-8d32e8b4-3493-49b4-94b8-f58f958e7b94.png)

类似的情况 , 我记的去年618也是这样, 然后一直手工做 T.T

**Comment by lionkingc** [comment]
已解决, 改成content = jumpButtons[i].parent().child(0).child(1).text()  即可, 多了个child(0)

**Comment by AN-535** [comment]
> 已解决, 改成content = jumpButtons[i].parent().child(0).child(1).text() 即可, 多了个child(0)

怎么搞？自己打包一个apk？

**Comment by lionkingc** [comment]
装autojs 4.1.1版本, 然后去作者的代码里的main分支下面下载start.js 源码 / 或者等作者确认是不是BUG及更新

刚试了能做,但好像有别的问题 , 菜单做着做着会变空白, 要重新开APP才行, 我换个版本的淘宝试试

**Comment by Eyion** [comment]
> 装autojs 4.1.1版本, 然后去作者的代码里的main分支下面下载start.js 源码 并按上面修改#130行 / 或者等作者确认是不是BUG及更新
> 
> 刚试了能做,但好像有别的问题 , 菜单做着做着会变空白, 要重新开APP才行, 我换个版本的淘宝试试

autojs的旧版在哪儿下的？现在官网都是pro了。要不还是等这边的脚本更新解决？

**Comment by lionkingc** [comment]
> > 装autojs 4.1.1版本, 然后去作者的代码里的main分支下面下载start.js 源码 并按上面修改#130行 / 或者等作者确认是不是BUG及更新
> > 刚试了能做,但好像有别的问题 , 菜单做着做着会变空白, 要重新开APP才行, 我换个版本的淘宝试试
> 
> autojs的旧版在哪儿下的？现在官网都是pro了。要不还是等这边的脚本更新解决？

忘记了, 好像也是百度找的

**Comment by QC2168** [comment]
> autojs的旧版在哪儿下的？现在官网都是pro了。要不还是等这边的脚本更新解决？
网上可以找到，第三方应用市场

**Comment by lionkingc** [comment]
![Screenshot_20221025-163147](https://user-images.githubusercontent.com/23330617/197726484-618e5f73-2bcc-4390-aeb4-ef977adcce2f.png)

我现在的情况是手工做,也会出现这情况 , 做着做着, 里面就白了, 不知道是我DNS的问题还是淘宝有防模拟器? 即使是手工操作,也会有概率变空白了..

**Comment by QC2168** [comment]
> ![Screenshot_20221025-163147](https://user-images.githubusercontent.com/23330617/197726484-618e5f73-2bcc-4390-aeb4-ef977adcce2f.png)
> 
> 我现在的情况是AUTOJS做着做着, 里面就空白了, 不知道是我DNS的问题还是淘宝有防模拟器? 即使是在模拟器里手工操作,也会有概率变空白..

我通过autojs打开的淘宝直接是访问不了

**Comment by QC2168** [comment]
> > 装autojs 4.1.1版本, 然后去作者的代码里的main分支下面下载start.js 源码 并按上面修改#130行 / 或者等作者确认是不是BUG及更新
> > 刚试了能做,但好像有别的问题 , 菜单做着做着会变空白, 要重新开APP才行, 我换个版本的淘宝试试
> 
> autojs的旧版在哪儿下的？现在官网都是pro了。要不还是等这边的脚本更新解决？

http://www.j9p.com/azrj/555458.html

**Comment by lionkingc** [comment]
> 

什么模拟器, 我用夜神自带的可以, 前几天用逍遥,四开就很卡,就放弃了

**Comment by lionkingc** [comment]
> > ![Screenshot_20221025-163147](https://user-images.githubusercontent.com/23330617/197726484-618e5f73-2bcc-4390-aeb4-ef977adcce2f.png)
> > 我现在的情况是AUTOJS做着做着, 里面就空白了, 不知道是我DNS的问题还是淘宝有防模拟器? 即使是在模拟器里手工操作,也会有概率变空白..
> 
> 我通过autojs打开的淘宝直接是访问不了


什么模拟器, 我用夜神自带的可以, 前几天用逍遥,四开就很卡,就放弃了

**Comment by Eyion** [comment]
所以应该不是模拟器的问题？

**Comment by MonsterNone** [comment]
@lionkingc 感谢。不同设备布局略有差异，新版增加上一个备用方式
