### ISSUE TITLE
淘宝，直播任务，完成无法返回。

### ISSUE THREAD

**Issue by RaKaiYli** [MonsterNone/tmall-miao#308]
淘宝双十一的喵果直播任务，完成后无法返回任务列表，需要关注之后并下单无法返回。

**Comment by chr19960719** [comment]
+1

**Comment by DaDa9299** [comment]
+1

**Comment by DaDa9299** [comment]
> 淘宝双十一的喵果直播任务，完成后无法返回任务列表，需要关注之后并下单无法返回。

关闭那些弹框后继续让他观看，过一会就回自动显示未检测到任务完成标识，接着自动运行程序

**Comment by MonsterNone** [comment]
> 需要关注之后并下单无法返回。

麻烦截图

**Comment by Ruler1020730** [comment]
+1 在这等了几分钟也不行

**Comment by ss-lb** [comment]
的确，有些直播间是退不回去的。比如说有弹窗的直播间，大概率退不回去。
