### ISSUE TITLE
当不能加入品牌会员时，会无限循环加入会员

### ISSUE THREAD

**Issue by linstwwwkid** [MonsterNone/tmall-miao#312]
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=4139699802924106515 skey=@crypt_d4d10689_5642a670c546f7807f79a33140324297 mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/64214533/197798117-70a35f50-13d6-4ec4-80ac-2df6d585f6d1.jpg)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=4707329266513027506 skey=@crypt_d4d10689_5642a670c546f7807f79a33140324297 mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/64214533/197798147-a0633080-0895-4350-bfa6-9efc7d9b45d6.jpg)

可能因为手机号之前被我注销过，提醒不能加入会员后，会无限重复这个操作卡死，能加一个无法加入就跳过的功能吗？
荣耀play4tp 鸿蒙2

**Comment by MonsterNone** [comment]
你说的“无法加入就跳过”实现起来有点困难，理论上这个任务未加入会员的话，返回任务列表后京东会换一个新的店铺，你那里能自动切换吗

**Comment by linstwwwkid** [comment]
> 你说的“无法加入就跳过”实现起来有点困难，理论上这个任务未加入会员的话，返回任务列表后京东会换一个新的店铺，你那里能自动切换吗

不能切换，返回后仍然是这家店铺，无限循环

**Comment by liu4113231988** [comment]
**能不能加个选项，是否完成入会任务，感谢**

**Comment by MonsterNone** [comment]
> **能不能加个选项，是否完成入会任务，感谢**

有啊，开始运行的时候

**Comment by MonsterNone** [comment]
> > 你说的“无法加入就跳过”实现起来有点困难，理论上这个任务未加入会员的话，返回任务列表后京东会换一个新的店铺，你那里能自动切换吗
> 
> 不能切换，返回后仍然是这家店铺，无限循环

好吧，这个情况暂时只能手动完成
