### ISSUE TITLE
京东更新到最新版后打开任务列表不识别了

### ISSUE THREAD

**Issue by keke1229488344** [MonsterNone/tmall-miao#324]
今天早上使用了三星自带的应用商店升级了京东（v11.3.2）导致无法使用，随后降级到Google Play版本v11.1.0 build98139，也无法正常使用。
脚本版本V15（昨晚V13还可以用的，但我尝试下回V13的脚本也不能运行，所以排除脚本问题，应该是京东手贱更新了...）
手机是Samsung OneUI4.1，Android12，Android System WebView版本106.0.5249.126（应该不是webview问题因为我京东没更新前使用v13脚本是正常使用的）
（或者作者可以发一下apk我安装试试...

![image](https://user-images.githubusercontent.com/17313185/197930287-06b4029f-90b9-4d70-8dd8-86ada7dc1aa8.png)

**Comment by MonsterNone** [comment]
我估计是，你之前使用的京东调用的是内置webview（似乎是腾讯tbs），后来更新之后，京东调用了系统webview（106版本），所以导致无法运行。

我这边的测试结果是，101及以上版本无法获取到内容动态更新（比如任务列表出现）之后的控件。

你可以试试在设置-应用管理里面找到webview卸载更新，不过三星系统可能内置的webview就是很高的版本。

**Comment by MonsterNone** [comment]
发现一个可能能解决问题的方法！（切换腾讯tbs内核）

我本地测试成功的步骤：
1. 给京东客服发送 `debugtbs.qq.com`，然后点击打开
2. 选择查看版本信息，观察第一个内核版本，是否有数据（如果运行不了任务应该为0，不确定）。
3. 选择安装线上内核，安装完成之后自动重启，查看下版本信息是否和刚刚不一样。
4. 运行任务尝试（可选强行停止京东APP）

**Comment by keke1229488344** [comment]
> 发现一个可能能解决问题的方法！（切换腾讯tbs内核）
> 
> 我本地测试成功的步骤：
> 
> 1. 给京东客服发送 `debugtbs.qq.com`，然后点击打开
> 2. 选择查看版本信息，观察第一个内核版本，是否有数据（如果运行不了任务应该为0，不确定）。
> 3. 选择安装线上内核，安装完成之后自动重启，查看下版本信息是否和刚刚不一样。
> 4. 运行任务尝试（可选强行停止京东APP）

第二步我的不是空，可以显示内核版本。
不过...第三步之后，就可以正常使用了，谢谢dalao

**Comment by korenamae** [comment]
安卓13这样子更新后重启，也能跑了，谢谢dalao
