### ISSUE TITLE
大佬我用模拟器淘宝不能做任务去

### ISSUE THREAD

**Issue by ladypiiiiiii** [MonsterNone/tmall-miao#333]
![35f0d7de4602f9f7085f6a5d815fce5](https://user-images.githubusercontent.com/116441305/198012001-f728d441-bd8e-47d6-af7f-f96b3abb8952.jpg)
因为模拟器有点卡所以进任务会白屏一阵，然后刚刷出来就提示未检测到任务完成标识，返回，然后又重新进等白屏，然后无限循环，换了个模拟器也不行

**Comment by raoji6** [comment]
> ![35f0d7de4602f9f7085f6a5d815fce5](https://user-images.githubusercontent.com/116441305/198012001-f728d441-bd8e-47d6-af7f-f96b3abb8952.jpg) 因为模拟器有点卡所以进任务会白屏一阵，然后刚刷出来就提示未检测到任务完成标识，返回，然后又重新进等白屏，然后无限循环，换了个模拟器也不行

我试了，不管手动还是脚本都是会出现白屏（网络加载慢），返回任务列表不刷新（大概率）。想要跑就用安卓机吧

**Comment by QC2168** [comment]
夜神可以跑得了，只是网络有点小慢

**Comment by MonsterNone** [comment]
淘宝最好不要用模拟器，容易黑
