### ISSUE TITLE
模拟器上任务重复问题

### ISSUE THREAD

**Issue by QC2168** [MonsterNone/tmall-miao#336]
新早出现任务重复问题，如下，完成了“租房补贴任务”之后，下一个任务还是”租房任务“
![image](https://user-images.githubusercontent.com/82024018/198171154-71eaac19-72ab-4572-a292-1447a5ed3f86.png)

**Comment by QC2168** [comment]
夜神模拟器 Android7.1.2版本

**Comment by MonsterNone** [comment]
淘宝最好不要用模拟器，容易黑
