### ISSUE TITLE
v9之后的版本打开就持续白屏无法退出

### ISSUE THREAD

**Issue by carlisleCL** [MonsterNone/tmall-miao#339]
机型一加7pro，系统OxygenOS 12.1

**Comment by MonsterNone** [comment]
脚本白屏？清除数据重新打开试试。

**Comment by carlisleCL** [comment]
> 脚本白屏？清除数据重新打开试试。

刚才测了一下v16版本，清除数据后打开，依旧白屏无反应。v9之前的版本都可以正常打开，就还挺奇怪的…

**Comment by MonsterNone** [comment]
抱歉，此问题不清楚情况，可能和V9之后的新UI有关。暂时没有OOS的设备可以测试。

**Comment by carlisleCL** [comment]
> 抱歉，此问题不清楚情况，可能和V9之后的新UI有关。暂时没有OOS的设备可以测试。

好的，我会在以后的版本继续测试的，目前测试模拟器中（

**Comment by carlisleCL** [comment]
> 抱歉，此问题不清楚情况，可能和V9之后的新UI有关。暂时没有OOS的设备可以测试。

实测v17版本可以继续使用了，十分感谢🙏
