### ISSUE TITLE
11.V16小米系统提示说有毒

### ISSUE THREAD

**Issue by cqxxbing** [MonsterNone/tmall-miao#343]
11.V16小米提示说有毒，不知道大家有没有这个提示，我最后还是相信github安装了的

**Comment by MonsterNone** [comment]
提示的病毒你仔细看一下，意思是`游戏外挂`🤭虽然我不懂小米是怎么判断的，但是看起来有点合理...

如果不放心可以自己用autojs下载代码运行

**Comment by cqxxbing** [comment]
已安装，使用中感觉自动滑动很慢，一点点的滑，不太像真实的滑动，不知道是不是我手机的原因   红米k20p

**Comment by MonsterNone** [comment]
> 已安装，使用中感觉自动滑动很慢，一点点的滑，不太像真实的滑动，不知道是不是我手机的原因 红米k20p

滑动确实如此，只是为了应付任务条件，对任务速度没有任何影响
