### ISSUE TITLE
V16问题

### ISSUE THREAD

**Issue by maxqq001** [MonsterNone/tmall-miao#344]
V16版开启了无障碍，但程序提示没有打开，
V15版本就无这个问题
手机： 一加8t

**Comment by MonsterNone** [comment]
你在设置-应用管理里面，强行停止应用，之后再试一下。或者直接重启手机。

**Comment by oxx116** [comment]
你好，会上新自动移动猫收集小麦的功能吗？

**Comment by MonsterNone** [comment]
@oxx116 不会
