### ISSUE TITLE
v16  红米k30至尊纪念版喵果总动员进入无法自动进行 获取

### ISSUE THREAD

**Issue by wangjiandream** [MonsterNone/tmall-miao#345]
![image](https://user-images.githubusercontent.com/84716121/198457180-c275dbe0-d9f4-4c43-85fc-a49cfaf907ff.png)
没法自动行走吃果子  （双开应用）

**Comment by wangjiandream** [comment]
当前环境为双开应用

**Comment by MonsterNone** [comment]
没有自动吃果子功能
