### ISSUE TITLE
会场任务浏览商品任务执行不完

### ISSUE THREAD

**Issue by administer888** [MonsterNone/tmall-miao#351]
![Screenshot_20221029_092059](https://user-images.githubusercontent.com/92105818/198755786-bda2a6ae-9d79-4890-a123-6e9225e52204.jpg)
vivo x60，京东和WebView都是最新版，一直往下翻页，翻了几页之后开始浏览，但是浏览6，7个后就自动返回了

**Comment by MonsterNone** [comment]
17版本以上的脚本会自动二次执行
