### ISSUE TITLE
最新版本v19京东任务进行模拟滑动时候报错

### ISSUE THREAD

**Issue by Tante2000** [MonsterNone/tmall-miao#356]
![QQ图片20221102110825](https://user-images.githubusercontent.com/53213635/199386300-efbe4d0f-e907-46ca-ac85-390b183cf290.jpg)
如图

**Comment by Sunltao** [comment]
me too

**Comment by Tante2000** [comment]
> 我也是

暂时先回退18版本，18版本正常

**Comment by MonsterNone** [comment]
20修复
