### ISSUE TITLE
v19 京东活动报错

### ISSUE THREAD

**Issue by Sunltao** [MonsterNone/tmall-miao#357]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/48008236/199387219-4210a34c-013b-4c1c-9268-5abeedc5aa75.png">
本人手机小米11u  12+256，系统版本 miui12.5.20

**Comment by Sunltao** [comment]
京东app 版本 v11.3.2

**Comment by flyinfox** [comment]
同样错误，用回v18了

**Comment by bigmengbig** [comment]
确实，荣耀也是这种情况

**Comment by MonsterNone** [comment]
20已修复
