### ISSUE TITLE
【急求】JD安装线上内核失败（之前点了清除tbs内核），求解谢谢！

### ISSUE THREAD

**Issue by laurel2001** [MonsterNone/tmall-miao#365]
机型：小米 10
问题截图：
![Screenshot_2022-11-11-22-08-25-508_com jingdong a](https://user-images.githubusercontent.com/86281537/201358019-2ce17338-5f63-4a49-95af-7ab779e706e1.jpg)

系统截图：
![Screenshot_2022-11-11-22-08-03-657-edit_com andro](https://user-images.githubusercontent.com/86281537/201358188-319272a5-561c-4e6f-8ea4-8a6be64838f0.jpg)

非常感谢！

**Comment by MonsterNone** [comment]
不好意思，这个问题我不清楚

**Comment by 357283670** [comment]
大佬，本次安卓8也无法安装线上内核。显示也是这个115错误

**Comment by 357283670** [comment]
@MonsterNone 忘了圈老大了
