### ISSUE TITLE
V2版本，华为P30无法检测到任务列表控件，更换完内核还是无法检测到

### ISSUE THREAD

**Issue by Inliang** [MonsterNone/tmall-miao#368]
V2版本，华为P30无法检测到任务列表控件，更换完内核还是无法检测到

**Comment by zj312** [comment]
红米k40也检测不到任务列表
![图片](https://user-images.githubusercontent.com/4038270/209510986-6dbeea67-872d-4423-bcf7-0a2a4ce9caed.png)

**Comment by number2021620** [comment]
还是不行啊V2~

**Comment by number2021620** [comment]
已经debugtbs.qq.com安装线上内核了

**Comment by number2021620** [comment]
只有X10有问题，我现在重新安装下京东试试

**Comment by number2021620** [comment]
怪了，V20跑起来了，X10没办法

**Comment by awhitewhale** [comment]
华为mate20也不行，和你一模一样的issue

**Comment by MonsterNone** [comment]
试试V3
