### ISSUE TITLE
大佬。这次没放js脚本了，求放出

### ISSUE THREAD

**Issue by lllrrr2** [MonsterNone/tmall-miao#372]
大佬。这次没放js脚本了，求放出

**Comment by MonsterNone** [comment]
源码稍后发布，目前流程还存在问题

**Comment by lllrrr2** [comment]
感谢大佬，

**Comment by sclodestar** [comment]
> 源码稍后发布，目前流程还存在问题

烦请贴一个进入领金币的字段，就是
app.startactivity
data .....

这段

**Comment by sclodestar** [comment]
e。。。我找到了，不能 用text找了。

**Comment by lllrrr2** [comment]
期待大佬再放个互助的脚本，我记得以前是有的，谢谢。

**Comment by MonsterNone** [comment]
@lllrrr2 一直都没有互助
