### ISSUE TITLE
红米K30S安装完成后点击软件无反应

### ISSUE THREAD

**Issue by sekurodesu** [MonsterNone/tmall-miao#378]
如题，点击软件后没有任何反应，无法进入软件，具体手机版本如下
![QQ图片20230523141445](https://github.com/MonsterNone/tmall-miao/assets/51750095/b3b1dd40-7287-41f2-87f1-7451c0fb1b1a)
![QQ图片20230523141617](https://github.com/MonsterNone/tmall-miao/assets/51750095/7d93e9e4-8324-4fd2-afbb-cbde951ac6ce)

**Comment by MonsterNone** [comment]
试试V2呢？

**Comment by sekurodesu** [comment]
试了V3版，现在正常了，感谢大佬
