### ISSUE TITLE
VMOS Pro虚拟机里安装后运行闪退

### ISSUE THREAD

**Issue by liwenhoneywell** [MonsterNone/tmall-miao#379]
VMOS Por 2.9.4 版本闪退

**Comment by tan0105** [comment]
+1   2.9.7打不开

**Comment by tan0105** [comment]
补充一下，是脚本apk在vmos里面打不开，闪退，用的rom是安卓7
宿主机正常

**Comment by epsgerry02** [comment]
一样

**Comment by tan0105** [comment]
刚才尝试在模拟器里安装autojs4.1.1版本，发现被强制提示版本过低，点击更新按钮直接崩溃。。。
找了个去掉版本验证的autojs，手动导入js后可以正常跑了

**Comment by liwenhoneywell** [comment]
手动导入虚拟机成功运行
