### ISSUE TITLE
红米7a 找不到任务入口

### ISSUE THREAD

**Issue by Charles147258** [MonsterNone/tmall-miao#38]
![80e1fe5673b2b426a9ebf1590f36793](https://user-images.githubusercontent.com/73870846/104912271-05774a80-59c7-11eb-87db-8c7ae93f50a7.jpg)

手机 红米 7a  系统miui11

**Comment by MonsterNone** [comment]
请具体描述

**Comment by Charles147258** [comment]
`
![80e1fe5673b2b426a9ebf1590f36793](https://user-images.githubusercontent.com/73870846/104912523-55561180-59c7-11eb-9948-b8c1887f6395.jpg)
`

**Comment by Charles147258** [comment]
之前手机太垃圾了才用不了，现在可以了，感谢
