### ISSUE TITLE
喜欢店铺任务异常

### ISSUE THREAD

**Issue by woniuxia** [MonsterNone/tmall-miao#380]
![64db296396e68d4cadce2b51e6ed1ae](https://github.com/MonsterNone/tmall-miao/assets/16383685/b4648cbc-9e44-4cab-b0bd-aae3724b4a5b)

**Comment by SansanTtm** [comment]
+1，我的红米K30P，安卓12，MIUI14也是异常

**Comment by MonsterNone** [comment]
这个问题暂时没遇到，有待研究

**Comment by woniuxia** [comment]
我这里可以稳定复现，需要提供哪些东西，能辅助排查

**Comment by SansanTtm** [comment]
![Uploading Screenshot_2023-05-23-16-26-31-419_com.jingdong.app.mall.jpg…]()
应该是定位不对

**Comment by MonsterNone** [comment]
一行代码在生产环境忘记去掉了/..V3修复
