### ISSUE TITLE
成功激活白条领立减卷-任务无法完成

### ISSUE THREAD

**Issue by mrleesiyu** [MonsterNone/tmall-miao#381]
老板好,存在这样一个问题, 因为是副号京东,所以实名下主号已经激活白条,副号无法完成激活,卡在这个任务无法通过进行下一个.
![微信图片_20230523142635](https://github.com/MonsterNone/tmall-miao/assets/102746529/a6e661b7-9341-4af4-810b-fbe221a915b0)

**Comment by MonsterNone** [comment]
v2
