### ISSUE TITLE
增加跳过激活白条的选项

### ISSUE THREAD

**Issue by aZerinChan** [MonsterNone/tmall-miao#384]
注销过白条的或者不想开白条的会一直卡在这个任务，无法进行下一个任务，建议增加一个跳过激活白条任务的选项
![image](https://github.com/MonsterNone/tmall-miao/assets/125354217/1f84f710-ef82-48ad-8b8c-dfcfe3d29199)

**Comment by MonsterNone** [comment]
使用V2
