### ISSUE TITLE
16:10分辨率导致脚本异常?经常找不到按钮

### ISSUE THREAD

**Issue by SKzxsk** [MonsterNone/tmall-miao#387]
虽然不是脚本的问题，但想问一下有没有其它解决办法？

用的平板，无论是横屏还是竖屏全屏展示都显示不全，上一回双11都还没这么水土不服，我看这次脚本信息有几个按钮直接是用分辨率为定位点？

**Comment by chiciko** [comment]
急用的话，搞个手机呗

**Comment by MonsterNone** [comment]
进行什么任务时失败？

目前版本的代码使用座标点击的只有京东“种草城”任务，其他还是用控件

**Comment by yunv7** [comment]
> 进行什么任务时失败？
> 
> 目前版本的代码使用座标点击的只有京东“种草城”任务，其他还是用控件

现在有两个毛病，一个是种草城时候显示读取到按钮坐标了，但是点击按钮动作无效，不知道是点错位置了还是什么原因；二是模拟滑动无效，做浏览任务时，不停提示进行模拟滑动，但是并没有滑动，还得经常手动去滑一下确保开始读秒
