### ISSUE TITLE
请问大佬，分身该如何设置，辛苦了！

### ISSUE THREAD

**Issue by LvDeShei** [MonsterNone/tmall-miao#388]
分身在原码中该如何设置？辛苦大佬指导一下，感谢！

**Comment by ilaotan** [comment]
小x分身 做的应用一样用呀  小米多开的也能用.   只是不要勾选自动打开app  手动进任务页面

**Comment by LvDeShei** [comment]
> 小x分身 做的应用一样用呀  小米多开的也能用.   只是不要勾选自动打开app  手动进任务页面

非常感谢！刚开始没仔细看，经大佬这一指导，设置成功了，再次表示感谢！
