### ISSUE TITLE
任务出错

### ISSUE THREAD

**Issue by mkcs121** [MonsterNone/tmall-miao#396]
预售幸运值浏览精选商店要等候15秒才算完成，脚本只等候一秒就返回

喵运会逛精选好物超过5秒没有滑动会暂停那个15秒倒数导致没法完成，有时候脚本会没有持续滑动

**Comment by mkcs121** [comment]
喵运会逛精选好物超过5秒没有滑动会暂停那个15秒倒数导致没法完成

**Comment by MonsterNone** [comment]
f1374282a2e11c2f2a19b701c2252a614df06ce0
5cd6582f4d15dc256d23a267bc1b5da5f518ae70
