### ISSUE TITLE
收益变成+10了

### ISSUE THREAD

**Issue by LegendAdmin** [MonsterNone/tmall-miao#397]
开始还是正常几万的，后来就变成每次只加10了

**Comment by nice-jiang** [comment]
+1

**Comment by tangguangliang** [comment]
+1

**Comment by Masterlovsky** [comment]
+1，收益会减少

**Comment by geekmark608** [comment]
+1，更换手机后手动做任务恢复正常，但继续使用助手仍会减少收益

**Comment by mustssr** [comment]
是的，手里只有淘宝和京东，其他APP和su都卸载了跑还是一样
更新App-5 618-J，新号新手机一样10

**Comment by brucethomaswayne6** [comment]
我没用这个软件跑TB，都被TB检测到了，现在设备黑了

**Comment by tangguangliang** [comment]
用最新版本测试了一下，淘宝任务还是+10

**Comment by GAOli-cong** [comment]
确实有此问题 只会增加10个金币

**Comment by weijiawei** [comment]
+1

**Comment by caihuahengyi-admin** [comment]
> 

+1

**Comment by PFFFei** [comment]
卸载并重启后手动做任务依然是+10 😭

**Comment by caihuahengyi-admin** [comment]
> 

> 卸载并重启后手动做任务依然是+10 😭

会黑号吗？寄。。

**Comment by lywsyxx** [comment]
我也碰到了这个问题

**Comment by Ctimes415** [comment]
只有10个 这是黑设备还是黑号了啊

**Comment by zrw-cxy** [comment]
> 

应该是黑设备，我换一台手机手冲就正常了

**Comment by zrw-cxy** [comment]
> 



> 只有10个 这是黑设备还是黑号了啊
应该是黑设备，我换一台手机手冲就正常了

**Comment by zrw-cxy** [comment]
> 只有10个 这是黑设备还是黑号了啊

应该是黑设备，我换一台手机手冲就正常了

**Comment by qxzg** [comment]
实测miui双开也可解决

**Comment by caihuahengyi-admin** [comment]
> 实测miui双开也可解决

请问双开是解决封号问题还是收益减少问题啊？

**Comment by qxzg** [comment]
> > 实测miui双开也可解决
> 
> 请问双开是解决封号问题还是收益减少问题啊？

解决收益变10的问题。
话说这个issue不就是讨论收益问题的吗，目前应该没有用这个被封号的吧？

**Comment by zrw-cxy** [comment]
> > > 实测miui双开也可解决
> > 
> > 请问双开是解决封号问题还是收益减少问题啊？
> 
> 解决收益变10的问题。
> 话说这个issue不就是讨论收益问题的吗，目前应该没有用这个被封号的吧？

可惜我测试的时候已经双开了，只能换设备了，无论重启、换网络环境、开代理、卸载、重装、更新系统都是解决不了，暂时怀疑是绑定了设备存储的某个东西，双开可以开辟新的东西，所以才变正常

**Comment by caihuahengyi-admin** [comment]
> > > 实测miui双开也可解决
> > 
> > 
> > 请问双开是解决封号问题还是收益减少问题啊？
> 
> 解决收益变10的问题。 话说这个issue不就是讨论收益问题的吗，目前应该没有用这个被封号的吧？

👍🏻楼上说有黑设备的吗不是😂是双开之后手动能解决问题还是用脚本也能收益正常？😳😳

**Comment by caihuahengyi-admin** [comment]
> 

好的，明白了，谢谢

**Comment by zrw-cxy** [comment]
> > > > 实测miui双开也可解决
> > > 
> > > 
> > > 请问双开是解决封号问题还是收益减少问题啊？
> > 
> > 解决收益变10的问题。 话说这个issue不就是讨论收益问题的吗，目前应该没有用这个被封号的吧？
> 
> 👍🏻楼上说有黑设备的吗不是😂是双开之后手动能解决问题还是用脚本也能收益正常？😳😳

千万别，不然就只能换设备了

**Comment by caihuahengyi-admin** [comment]
> > > > > 实测miui双开也可解决
> > > > 
> > > > 
> > > > 请问双开是解决封号问题还是收益减少问题啊？
> > > 
> > > 
> > > 解决收益变10的问题。 话说这个issue不就是讨论收益问题的吗，目前应该没有用这个被封号的吧？
> > 
> > 
> > 👍🏻楼上说有黑设备的吗不是😂是双开之后手动能解决问题还是用脚本也能收益正常？😳😳
> 
> 千万别，不然就只能换设备了

好的好的，谢谢了😭

**Comment by brucethomaswayne6** [comment]
> 可惜我测试的时候已经双开了，只能换设备了，无论重启、换网络环境、开代理、卸载、重装、更新系统都是解决不了，暂时怀疑是绑定了设备存储的某个东西，双开可以开辟新的东西，所以才变正常

可以试试删除双开账户(会重启)，然后重新双开看看 @zrw-cxy

**Comment by Masterlovsky** [comment]
最新更新的版本好像不会降低收益了，但是之前已经降得号不知道怎么解救出来，大家有法子吗？

**Comment by PFFFei** [comment]
> 卸载并重启后手动做任务依然是+10 😭

我删除应用数据并卸载重启都没用，手动操作收益是+100，我手机有个双开应用，手动收益恢复了，等我测试一下再回来

**Comment by PFFFei** [comment]
> > 卸载并重启后手动做任务依然是+10 😭
> 
> 我删除应用数据并卸载重启都没用，手动操作收益是+100，我手机有个双开应用，手动收益恢复了，等我测试一下再回来

已测试完毕，收益正常。（同一个账号、同一个设备、不同的双开应用）

**Comment by caihuahengyi-admin** [comment]
> 

手动还是用脚本？都正常了吗？

**Comment by PFFFei** [comment]
脚本，目前看一切正常

**Comment by lywsyxx** [comment]
感谢测试，我已经被+10困扰好久了😭

________________________________

**Comment by caihuahengyi-admin** [comment]
我之前用脚本收益+10，但是手动收益正常，这应该不算是黑设备吧😭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月30日(周二) 下午3:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MonsterNone/tmall-miao] 收益变成+10了 (Issue #397)




 
脚本，目前看一切正常

**Comment by JacentLeung** [comment]
双开应用还是+100

**Comment by lywsyxx** [comment]
我双开淘宝手动做任务试了一下，还是没有恢复正常

**Comment by MonsterNone** [comment]
app-6已经过检测。黑设备的等24小时尝试

**Comment by cannotsay** [comment]
换了个新设备，手动还是+100，估计号废了。无所谓了，本来就没打算做618任务，只是看到了脚本，才想起来跑跑

**Comment by chajie0709** [comment]
> 换了个新设备，手动还是+100，估计号废了。无所谓了，本来就没打算做618任务，只是看到了脚本，才想起来跑跑

我也是，昨天黑设备，换设备恢复了。今天直接黑号不让玩了

**Comment by FH0904** [comment]
收益+10

**Comment by JunShine** [comment]
我估计是用了非残黑的，但是很奇怪刷机后没装什么东西的淘宝还是黑的，怎么黑设备的？
