### ISSUE TITLE
任务无法正常执行(华为Nova 7+EMUI11.0)

### ISSUE THREAD

**Issue by GOOD-AN** [MonsterNone/tmall-miao#40]
淘宝年货节提示无法自动
![image](https://user-images.githubusercontent.com/53306377/105439747-570e2680-5ca0-11eb-9f90-5936b4d9f842.png)
蚂蚁森林提示无法找到入口
![image](https://user-images.githubusercontent.com/53306377/105439780-68efc980-5ca0-11eb-84f6-13259397029c.png)

**Comment by MonsterNone** [comment]
麻烦提供具体截图

**Comment by GOOD-AN** [comment]
截图已经上传，我的这面截图显示正常，如果需要，我会再次上传截图

**Comment by GOOD-AN** [comment]
![Screenshot_20210122_105019_com taobao taobao](https://user-images.githubusercontent.com/53306377/105628700-65636a80-5e79-11eb-80c0-89fe3336aa8c.jpg)
![Screenshot_20210122_105249_com taobao taobao](https://user-images.githubusercontent.com/53306377/105628702-698f8800-5e79-11eb-8c51-8db2c1e553ec.jpg)
截图已经上传，我的这面截图显示正常，我重新上传一下截图，这个应该没有问题了。

**Comment by MonsterNone** [comment]
不好意思，没挂vpn图片没显示...

领红包页面是需要手动的；任务入口是因为淘宝自动给你跳转到了普通的芭芭农场，需要在脚本运行的同时点一下右侧的小箭头切换
