### ISSUE TITLE
卡在小程序任务中无法完成

### ISSUE THREAD

**Issue by 970844297** [MonsterNone/tmall-miao#403]
![Screenshot_2023-05-30-02-52-09-538_com jingdong app mall](https://github.com/MonsterNone/tmall-miao/assets/49755767/475fc852-d2ec-406d-bdc9-58d00f6cc261)
京东任务会卡在如图的小程序任务中，无法完成，一直循环 跳转小程序--返回。小米mix2s和魅族13均出现该问题，前者有微信分身，后者没有。
助手版本号app-5_2023618-J

**Comment by MonsterNone** [comment]
好的，下个版本跳过此任务
