### ISSUE TITLE
淘宝任务 点进去直接返回时间不够15秒任务无法完成无限循环

### ISSUE THREAD

**Issue by LiGithubYu** [MonsterNone/tmall-miao#404]
![Screenshot_2023-05-30-10-45-40-631_com taobao taobao](https://github.com/MonsterNone/tmall-miao/assets/48920551/db2d626e-8f8b-4ce7-8d9b-7c0e6d14f90f)

**Comment by cannotsay** [comment]
我也遇到了

**Comment by zrw-cxy** [comment]
你们没被淘宝检测吗？猫币都是正常获取莫？

**Comment by geelinsir** [comment]
> 你们没被淘宝检测吗？猫币都是正常获取莫？

昨天10个币，今天100币

**Comment by geelinsir** [comment]
这个问题是倒计时控件没加载出来吧，我昨天也遇到了过一会重进就恢复了

**Comment by zrw-cxy** [comment]
> > 你们没被淘宝检测吗？猫币都是正常获取莫？
> 
> 昨天10个币，今天100币

我也是100币，请问手冲的还是用软件@geelinsir

**Comment by geelinsir** [comment]
> > > 你们没被淘宝检测吗？猫币都是正常获取莫？
> > 
> > 
> > 昨天10个币，今天100币
> 
> 我也是100币，请问手冲的还是用软件@geelinsir

设备黑了，啥都是

**Comment by zrw-cxy** [comment]
> 



> > > > 你们没被淘宝检测吗？猫币都是正常获取莫？
> > > 
> > > 
> > > 昨天10个币，今天100币
> > 
> > 
> > 我也是100币，请问手冲的还是用软件@geelinsir
> 
> 设备黑了，啥都是

嗯嗯我知道，我是想着如果继续用的话会不会变成10币哈哈哈，不用软件的话估计明天变成1000币

**Comment by MonsterNone** [comment]
> > 
> 
> > > > > 你们没被淘宝检测吗？猫币都是正常获取莫？
> > > > 
> > > > 
> > > > 昨天10个币，今天100币
> > > 
> > > 
> > > 我也是100币，请问手冲的还是用软件@geelinsir
> > 
> > 
> > 设备黑了，啥都是
> 
> 嗯嗯我知道，我是想着如果继续用的话会不会变成10币哈哈哈，不用软件的话估计明天变成1000币

现在app-6已经能过检测了，黑设备一般24小时恢复

**Comment by zrw-cxy** [comment]
测试了可以了，太棒啦[爱心]@MonsterNone

**Comment by MonsterNone** [comment]
@LiGithubYu 我这边测试这个任务没发现异常，暂时无法确定bug来源
