### ISSUE TITLE
小米手机--请在手机管家-病毒查杀中移除管控

### ISSUE THREAD

**Issue by fafa1688123** [MonsterNone/tmall-miao#408]
小米12pro 点击运行提示请在手机管家-病毒查杀中移除管控

**Comment by ilaotan** [comment]
无非几个选择：
相信管家 卸载脚本
不相信管家 信任脚本

**Comment by fafa1688123** [comment]
手机上找不到病毒查杀中移除管控

**Comment by fafa1688123** [comment]
安装成功，就是授予悬浮窗权限 提示这个，权限有给了，就是提示这个启动不起来

**Comment by fafa1688123** [comment]
刚试了下，不管那个提示，直接执行任务 是可以的=。=

**Comment by MonsterNone** [comment]
@fafa1688123 小米在，手机管家-病毒扫描-设置-白名单里面，添加忽略
