### ISSUE TITLE
最新版足力健直播间任务无法返回啊

### ISSUE THREAD

**Issue by chen4ye** [MonsterNone/tmall-miao#411]
最新版进入足力健直播间后就无法返回了，一直卡在直播间

**Comment by chen4ye** [comment]
其他直播也是，提示“开始检测任务完成，部分控件无法检测，会在30秒后自动返回，请耐心等待”。但是一直没退出去，一直卡在直播间无法继续其他任务。手机是华为DUAL LENS,比较旧的

**Comment by MonsterNone** [comment]
可能是后台卡顿了，内存不足之类的原因。因为直播比较吃性能。另外直播间的模拟滑动会导致任务提示消失，这个问题之后修复。
