### ISSUE TITLE
淘宝任务奖励只有100喵币了

### ISSUE THREAD

**Issue by xiao-xiaol** [MonsterNone/tmall-miao#416]
做淘宝任务只奖励100喵币了，这个是为什么会被淘宝检测到？有什么办法防范吗？

**Comment by jacksls** [comment]
看来大家都一样呀，手机被标记成作弊了，不知道作者能修复不

**Comment by ilaotan** [comment]
是最新版吗？ 我用老app跑的，黑了好几天，现在已经恢复了，目前最新app跑没再拉黑

**Comment by xiao-xiaol** [comment]
已经恢复了，重新装了最新版的app就可以了。应该是淘宝检测到了手机内的旧版app
