### ISSUE TITLE
该更新啦！

### ISSUE THREAD

**Issue by junwang0204** [MonsterNone/tmall-miao#420]
淘宝京东今晚好像双十一就开始了，淘宝预售已经上线了，大大加油！

**Comment by P3R5T7U9** [comment]
> 淘宝京东今晚好像双十一就开始了，淘宝预售已经上线了，大大加油！

兄de，麻烦你先翻下此仓库的Release部分，Monster大早从前晚就更新某宝预售的脚本了，昨晚又继续连更两个版本，另外，在此仓库的文件夹中有个“tb_luck.js”，也是昨晚才更新的脚本。。。

**Comment by cy920820** [comment]
京东还没任务吧

**Comment by MonsterNone** [comment]
> > 淘宝京东今晚好像双十一就开始了，淘宝预售已经上线了，大大加油！
> 
> 兄de，麻烦你先翻下此仓库的Release部分，Monster大早在前晚就更新某宝预售的脚本了，昨晚又继续连更两个版本，另外，在此仓库的文件夹中有个“tb_luck.js”，也是昨晚才更新的脚本。。。

谢谢~ 任务代码已经上传，打包版也发在release里面了。

淘宝主活动25日0点上线。京东活动目前没消息，不知道还有没有。

**Comment by geelinsir** [comment]
淘宝活动上线了
https://m.tb.cn/h.5SislIY?tk=uzt6W1F8W7L CZ3457

**Comment by geelinsir** [comment]
同时淘宝目前已开启三个能量任务，分别是
主会场能量任务
17￥ CZ0001 nLntW1FJGtv￥ https://m.tb.cn/h.5SRbN5j  助我领红包
预售会场能量任务
67￥ CZ3457 7ITsW1FIiyw￥ https://m.tb.cn/h.57ZnNs5  快助我领红包！
福利购能量任务
39₤Bk80W1FGcnC🗝 https://m.tb.cn/h.5SRXy5y  CZ3457 我分享给你了一个超赞的内容，快来看看吧
