### ISSUE TITLE
手动升到5级，打开提示无法进入任务列表。

### ISSUE THREAD

**Issue by qif580231** [MonsterNone/tmall-miao#426]
![Screenshot_2023-10-25-10-35-10-729_com taobao tao](https://github.com/MonsterNone/tmall-miao/assets/48021642/fee112f1-a166-40c3-a899-72cceb5769f4)

**Comment by MonsterNone** [comment]
装了lsposed吗？降级到1.8.6才能运行。没装的话重启手机试试

**Comment by qif580231** [comment]
还真是装了，换个手机搞起来。
