### ISSUE TITLE
每次浏览任务金币奖励才200

### ISSUE THREAD

**Issue by kaikai13116089** [MonsterNone/tmall-miao#43]
小米8淘宝最新版本

**Comment by MonsterNone** [comment]
是否安装了其他辅助，或autojs等使用无障碍服务的软件

**Comment by kaikai13116089** [comment]
> 是否安装了其他辅助，或autojs等使用无障碍服务的软件

对，有autojs

**Comment by MonsterNone** [comment]
> > 是否安装了其他辅助，或autojs等使用无障碍服务的软件
> 
> 对，有autojs

淘宝会检测autojs的兄弟。试试双开淘宝，或者删除autojs，或者在vmos之类的虚拟机里面运行。

**Comment by yangkai77** [comment]
小号开10000感觉被削了
