### ISSUE TITLE
京东的脚本是不是有问题？

### ISSUE THREAD

**Issue by wingswing1** [MonsterNone/tmall-miao#430]
用的代码版，运行start_jd跳转618活动结束

**Comment by sunzeren** [comment]
一样，直接跳转到活动结束了

**Comment by kinghunki** [comment]
> 用的代码版，运行start_jd跳转618活动结束

京东活动还没有开始，代码还是之前618的代码！

**Comment by MonsterNone** [comment]
如楼上，jd这次可能没有任务了，只有一个jd_hb.js任务
