### ISSUE TITLE
红包任务中浏览十个商品，检测不到商品数量

### ISSUE THREAD

**Issue by KarsonYu** [MonsterNone/tmall-miao#435]
一直显示为0，导致一直翻页

**Comment by neilzhengzx** [comment]
最新版无法识别任务,下载昨天的版本,点击不更新code可以识别

**Comment by KarsonYu** [comment]
> 最新版无法识别任务,下载昨天的版本,点击不更新code可以识别

幻想岛任务开始就结束

**Comment by neilzhengzx** [comment]
> > 最新版无法识别任务,下载昨天的版本,点击不更新code可以识别
> 
> 幻想岛任务开始就结束

可以先下载昨天发布的apk,安装后,弹窗提示是否更新code,点击否, 然后运行可以执行任务.

**Comment by KarsonYu** [comment]
> > > 最新版无法识别任务,下载昨天的版本,点击不更新code可以识别
> > 
> > 
> > 幻想岛任务开始就结束
> 
> 可以先下载昨天发布的apk,安装后,弹窗提示是否更新code,点击否, 然后运行可以执行任务.

[App-6 1111-G](https://github.com/MonsterNone/tmall-miao/releases/tag/230032) 这个版本嘛？

**Comment by MonsterNone** [comment]
幻想岛已经修复了

**Comment by MonsterNone** [comment]
商品问题和版本没太大关系，我研究研究具体原因
