### ISSUE TITLE
大佬，2024年618会不会搞

### ISSUE THREAD

**Issue by Wzhuaboy** [MonsterNone/tmall-miao#446]
大佬，2024年618会不会搞

**Comment by MonsterNone** [comment]
有

**Comment by haiya512** [comment]
> 有

大佬，京东好像关闭了通过发送客服消息打开安装内核的入口。还是说我进入的方法不对？
我进入的方法：打开京东APP，点击我的，点击我的消息，直接发送消息给京东客服。

至于APP上提示的，打开客服服务发送消息，“客户服务“我打开了，发送消息，没看到入口在哪里

**Comment by MonsterNone** [comment]
> > 有
> 
> 大佬，京东好像关闭了通过发送客服消息打开安装内核的入口。还是说我进入的方法不对？ 我进入的方法：打开京东APP，点击我的，点击我的消息，直接发送消息给京东客服。
> 
> 至于APP上提示的，打开客服服务发送消息，“客户服务“我打开了，发送消息，没看到入口在哪里

发给客服之后，直接点击你自己发的链接
