### ISSUE TITLE
双11淘宝京东活动开始了，请求更新

### ISSUE THREAD

**Issue by refwww** [MonsterNone/tmall-miao#448]
淘宝和京东的活动14号开始了，请求更新

**Comment by opem07** [comment]
_➕1_

**Comment by opem07** [comment]
_➕1_

**Comment by geelinsir** [comment]
双十一版本已发布，软件启动后自动检查更新，已有618版本的无须重新下载
++++++++++++++++++++++
注意：云盘链接一直是同一个，链接中会持续上传新版。
++++++++++++++++++++++
下载地址：https://www.123pan.com/s/thJ1jv-VtpsA.html 提取码:LtGD
++++++++++++++++++++++

**Comment by elsenjang** [comment]
好像京东无法开始，是我个人的问题还是软件的问题？

**Comment by gh125** [comment]
> 好像京东无法开始，是我个人的问题还是软件的问题？

京东还没开始

**Comment by xiaoxiyao** [comment]
不开源了吗，没看到源码更新
