### ISSUE TITLE
显示手动滑回主页面就一直卡住了

### ISSUE THREAD

**Issue by 13071558875** [MonsterNone/tmall-miao#46]
目测需要增加一个弹窗检测，有的任务会有弹窗广告。完成后就检测不到了

**Comment by 13071558875** [comment]
> 目测需要增加一个弹窗检测，有的任务会有弹窗广告。完成后就检测不到了

然年整个脚本就挂了，怎么运行都是进到主会场，显示该页面无法运行需手动

**Comment by MonsterNone** [comment]
> > 目测需要增加一个弹窗检测，有的任务会有弹窗广告。完成后就检测不到了
> 
> 然年整个脚本就挂了，怎么运行都是进到主会场，显示该页面无法运行需手动

手动运行应该是领红包页面吧？
