### ISSUE TITLE
怎么一键完成农场施肥，还有支付宝任务问题

### ISSUE THREAD

**Issue by 13071558875** [MonsterNone/tmall-miao#49]
大佬打算整合全部脚本吗

**Comment by MonsterNone** [comment]
> 大佬打算整合全部脚本吗
暂时没有这个打算

支付宝因为比较敏感，所以就不自动操作了。实际上支付宝的浏览任务，只要开始倒计时之后，直接返回就能领到金币了，不用等15秒。
