### ISSUE TITLE
浏览15秒的任务，两秒左右就自动返回了

### ISSUE THREAD

**Issue by pasteleft** [MonsterNone/tmall-miao#52]
版本为5月31日更新的最新版本V2021613-3
手机版本为 红米K30ultra miui12.0.21
淘宝版本为最新版 10.0.0
![Screenshot_2021-05-31-10-30-18-591_com github MonsterNone](https://user-images.githubusercontent.com/82921815/120131837-ca63ff80-c18e-11eb-929c-5e8830efa1e2.jpg)

**Comment by MonsterNone** [comment]
谢谢！已经修好
