### ISSUE TITLE
会卡到充话费领喵币，不能往下执行后面的任务

### ISSUE THREAD

**Issue by jk9527** [MonsterNone/tmall-miao#53]
如题，需要添加判断跳过充话费领喵币。

**Comment by MonsterNone** [comment]
有没有截图，我还没刷到充话费任务

**Comment by jk9527** [comment]
![微信图片_20210531164453](https://user-images.githubusercontent.com/40191829/120167026-d5bb3780-c22f-11eb-88a1-ce2e65571873.jpg)
![f72b67976ea51218370b23fdc8c78d6](https://user-images.githubusercontent.com/40191829/120167039-d9e75500-c22f-11eb-8192-c7dc0d9b1b38.jpg)
充话费任务要充值才能完成，会卡住不往下做任务。

**Comment by MonsterNone** [comment]
收到，下个版本修复，谢谢

**Comment by MonsterNone** [comment]
2021618-5已修复
