### ISSUE TITLE
苹果版

### ISSUE THREAD

**Issue by alibaipang** [MonsterNone/tmall-miao#54]
苹果版支持吗、电脑版的啥时候出来呀、大佬

**Comment by MonsterNone** [comment]
苹果版暂时还没有哈（主要是没有iphone:(
电脑版也是安卓的，你可以先电脑用安卓模拟器试试看

**Comment by MonsterNone** [comment]
苹果版使用比较繁琐，暂时没有开发计划，谢谢~

**Comment by alibaipang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    京东的活动有吗、电脑版的
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1928096127
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年6月3日 ***@***.***> 写道： 




苹果版使用比较繁琐，暂时没有开发计划，谢谢~



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
