### ISSUE TITLE
小问题反馈

### ISSUE THREAD

**Issue by zhaimuyanxian** [MonsterNone/tmall-miao#55]
![1](https://user-images.githubusercontent.com/46186761/120203875-c4d3eb80-c25a-11eb-8485-fb30e9d4509a.png)
做日常任务中遇到这个页面会暂停，返回主界面再次重新启动后没出现其他问题

**Comment by MonsterNone** [comment]
收到！这个问题偶尔出现，都没找到复现修复验证的机会哈哈，等哪天我瞅见了修一下

**Comment by zhaimuyanxian** [comment]
其实也不是很影响，我操作过程就触发过一次，手动修正一下就好了，感谢的你分享(๑•̀ㅂ•́)و✧
