### ISSUE TITLE
一直都不出现任务标识

### ISSUE THREAD

**Issue by liziming1997** [MonsterNone/tmall-miao#56]
一直都不出现任务标识
![Snipaste_2021-06-01_10-32-43](https://user-images.githubusercontent.com/40463225/120258527-ce923900-c2c4-11eb-9aa3-9a0719b97bd2.jpg)

**Comment by MonsterNone** [comment]
什么版本的淘宝？手机是什么型号？
应该和淘宝有关，这个页面上就没有任务标识存在。
