### ISSUE TITLE
执行完累计任务进度条的任务后，下面的其他任务不执行

### ISSUE THREAD

**Issue by openye** [MonsterNone/tmall-miao#58]
![微信图片_20210601204958](https://user-images.githubusercontent.com/53599830/120326168-0330df80-c31b-11eb-8a0d-9c29f1578ca8.jpg)
![微信图片_20210601204953](https://user-images.githubusercontent.com/53599830/120326173-04620c80-c31b-11eb-8804-b78f9538752e.jpg)
![微信图片_20210601204940](https://user-images.githubusercontent.com/53599830/120326181-05933980-c31b-11eb-9b62-acca5144c235.jpg)
手机是荣耀10

**Comment by MonsterNone** [comment]
这些剩下的任务都太复杂了，很多需要手动操作，所以默认脚本不会自动完成。
