### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by texasdream** [MonsterNone/tmall-miao#6]
大佬，能不能把各种点击操作也都弄成随机位置的，包括后续的，按钮有大小，然后随机点击按钮的所在区域，一定范围内随机拍拍猫，页面内也随机滑动一下等等，并且在每次操作后随机时延，尽可能的模拟人的操作。

**Comment by MonsterNone** [comment]
目前点击是直接点击文本控件，这个可能没法做成随机😂滑动也是，都是直接调用无障碍操作控件的

**Comment by kevin-xk** [comment]
去逛逛的任务完不成，匹配的关键字，需要多加几个，谢谢

**Comment by MonsterNone** [comment]
> 去逛逛的任务完不成，匹配的关键字，需要多加几个，谢谢

好的

**Comment by texasdream** [comment]
拍猫猫可以加吧，还有可以把每次操作后增加随机的时延，这个应该不难
