### ISSUE TITLE
直播类店铺任务不会自动返回

### ISSUE THREAD

**Issue by pasteleft** [MonsterNone/tmall-miao#64]
机型：红米K30Ultra
版本：MIUI 12.5
![Screenshot_2021-06-06-09-32-40-435_com taobao taobao](https://user-images.githubusercontent.com/82921815/120909792-5607ef80-c6ab-11eb-9650-6df6d556301a.jpg)

**Comment by MonsterNone** [comment]
可能是没显示出任务图标emm
你的淘宝是什么版本
