### ISSUE TITLE
任务列表打不开

### ISSUE THREAD

**Issue by LJW2959** [MonsterNone/tmall-miao#70]
小米11，安卓12，miui开发版10.13，打开任务列表无反应

![Screenshot_2021-10-20-19-41-14-745_com android settings](https://user-images.githubusercontent.com/34470864/138087054-ca2ff6fb-0bce-4e87-bcec-b5041f225810.jpg)
![Screenshot_2021-10-20-19-40-55-858_com jingdong app mall](https://user-images.githubusercontent.com/34470864/138087073-dbf14293-784b-4367-b42d-0b8fcc81c72f.jpg)

**Comment by bilibili20001** [comment]
索尼也是 安卓11

**Comment by Iy204** [comment]
Pixel Experience android 11 任务列表报错
`TypeError: Cannot find function clickable in object com.stardust.automator.UiObjectCollection@78a8e38. (/storage/emulated/0/脚本/start_jd.js#81)
TypeError: Cannot find function clickable in object com.stardust.automator.UiObjectCollection@78a8e38.
    at /storage/emulated/0/脚本/start_jd.js:81:0`

**Comment by LJW2959** [comment]
最新版（双十一活动第四版）还是这样

**Comment by MonsterNone** [comment]
> Pixel Experience android 11 任务列表报错 `TypeError: Cannot find function clickable in object com.stardust.automator.UiObjectCollection@78a8e38. (/storage/emulated/0/脚本/start_jd.js#81) TypeError: Cannot find function clickable in object com.stardust.automator.UiObjectCollection@78a8e38. at /storage/emulated/0/脚本/start_jd.js:81:0`

应该是这个原因，但是看源码也不至于啊，我再研究一下

**Comment by MonsterNone** [comment]
> v7也不行，提示这个 ![Screenshot_2021-10-21-17-36-20-429_com jingdong app mall](https://user-images.githubusercontent.com/34470864/138252033-26d9421d-b063-429e-a9b9-c84cabfe9ea1.jpg)

麻烦试试V14及以上
