### ISSUE TITLE
v13--雷电模拟器开可以京东，不能通过淘宝安全检测，但10点后京东进活动界面一直闪退

### ISSUE THREAD

**Issue by 476822172** [MonsterNone/tmall-miao#80]
![Screenshot_20211021-182559](https://user-images.githubusercontent.com/59389122/138259793-ed663a60-c306-4d7c-8ecb-1b3765c41979.png)
卡在寻找任务了

**Comment by HAHA009** [comment]
是淘宝不给你在模拟器用 你换啥外挂都不行

**Comment by aaddq** [comment]
25年来考古
现在淘宝查模拟器严多了，登录时拖验证滑块没过，然后直接限制登陆了
<img width="1121" height="111" alt="Image" src="https://github.com/user-attachments/assets/5a3f6b76-95c0-4f2b-aee8-8374ef84800c" />
