### ISSUE TITLE
京东 入会任务  脚本bug

### ISSUE THREAD

**Issue by zyyv** [MonsterNone/tmall-miao#81]
里面的判断不通过，无法返回

```
console.log('等待返回...')
let r = textMatch(/.*累计任务奖.*|.*礼包.*/).findOne(8000)
if (!r.text().match(/累计任务奖/)) {
  back()
}
```
--------------------------------
目前发现京东的入会任务会自动返回。

![image](https://user-images.githubusercontent.com/42139754/138261100-cec44cdb-6417-4c73-a88f-9d3cebab2b23.png)

**Comment by chris-zhu** [comment]
> 这` textMatch(/.*累计任务奖.*|.*礼包.*/).findOne(8000)`是等待自动返回，检测任务列表的判断

好的，可能是我没仔细阅读源码。但是入会任务确实是会卡住

![image](https://user-images.githubusercontent.com/42139754/138263130-2318738b-2770-4714-bf34-3b7cd1ee9c8a.png)
