### ISSUE TITLE
淘宝直播不能自动退出

### ISSUE THREAD

**Issue by 935039168** [MonsterNone/tmall-miao#90]
版本：淘宝10.0.0
设备：三星S9+
问题：做任务进入直播页面以后不能自动退出

**Comment by qlindazm** [comment]
同样的问题，

版本：淘宝10.1.0
设备：小米8se
log：未检测到任务完成标识。退出；[JavaException:...ScriptInterruptedException:null]

**Comment by MonsterNone** [comment]
淘宝有点老，更新一下吧

**Comment by MonsterNone** [comment]
> 建议加一个判断 退出后判断是不是有任务列表 没有再退出一次 连续两个退出 还没任务列表 再判断任务终止 很多情况 进入直播 或者某个店铺 弹个小窗口 第一次返回只是关闭窗口 第二次才能回到列表

好，考虑加入
