### ISSUE TITLE
京东加购任务报错

### ISSUE THREAD

**Issue by XiaoTianJianJun** [MonsterNone/tmall-miao#94]
红米K40 
京东加购任务报错
[JavaException: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5]

**Comment by MonsterNone** [comment]
可能是因为京东在小米机型上页面布局不一样，暂时不太好修，因为没有小米设备测试

**Comment by MonsterNone** [comment]
如果有朋友帮忙用AutoJS看一下购物车按钮的`indexInParent`属性和在页面层次中查看就好了
